# Makefile for CNSS platform driver

obj-$(CONFIG_CNSS)	+= cnss_pci.o
obj-$(CONFIG_CNSS)	+= cnss_sdio.o
obj-$(CONFIG_CNSS_LOGGER)	+= logger/

obj-$(CONFIG_CNSS)	+= cnss_common.o
obj-$(CONFIG_HTC_WLAN_NV) += custom_platdev.o
