obj-$(CONFIG_TEST)		+= test.o mock.o common-mocks.o string-stream.o \
  test-stream.o
obj-$(CONFIG_TEST_TEST)		+= \
  test-test.o test-mock.o mock-macro-test.o mock-test.o string-stream-test.o
obj-$(CONFIG_EXAMPLE_TEST)	+= example-test.o
