#
# Makefile for the focaltech FT3207 touchscreen drivers.
#


obj-$(CONFIG_TOUCHSCREEN_FT3207) += ft_3207.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_core.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_ctl.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_ex_fun.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_flash.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += test_lib.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += ini.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += Global.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += Config_FT6X36.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += Test_FT6X36.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += DetailThreshold.o
ft_3207-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_gesture.o
