#
# Makefile for the focaltech FT3207 touchscreen drivers.
#


obj-$(CONFIG_TOUCHSCREEN_FT3207) += fts_ts.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_core.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_ctl.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_ex_fun.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_flash.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += test_lib.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += ini.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += Global.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += Config_FT6X36.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += Test_FT6X36.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += DetailThreshold.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3207) += focaltech_gesture.o
