
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_sensor_module/cam_sensor
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_vsync_dev.o
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_vsync_pb.o
