/*
 * iaxxx-register-defs-in-endpoint-group.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_IN_EP_GRP_H__
#define __IAXXX_REGISTER_DEFS_IN_EP_GRP_H__

/*** The base address for this set of registers ***/
#define IAXXX_IN_EP_GRP_REGS_ADDR (0x00000000)

/*** IN_EP_GRP_CONNECT (0x00000000) ***/
/*
 */
#define IAXXX_IN_EP_GRP_CONNECT_ADDR (0x00000000)
#define IAXXX_IN_EP_GRP_CONNECT_MASK_VAL 0x0000ffff
#define IAXXX_IN_EP_GRP_CONNECT_RMASK_VAL 0x0000ffff
#define IAXXX_IN_EP_GRP_CONNECT_WMASK_VAL 0x0000ffff
#define IAXXX_IN_EP_GRP_CONNECT_RESET_VAL 0x00000000

/*
 * System ID of the source endpoint feeding this endpoint
 */
#define IAXXX_IN_EP_GRP_CONNECT_SOURCE_ID_MASK 0x0000ffff
#define IAXXX_IN_EP_GRP_CONNECT_SOURCE_ID_RESET_VAL 0x0
#define IAXXX_IN_EP_GRP_CONNECT_SOURCE_ID_POS 0
#define IAXXX_IN_EP_GRP_CONNECT_SOURCE_ID_SIZE 16

/*** IN_EP_GRP_STATUS (0x00000004) ***/
/*
 */
#define IAXXX_IN_EP_GRP_STATUS_ADDR (0x00000004)
#define IAXXX_IN_EP_GRP_STATUS_MASK_VAL 0xffff0003
#define IAXXX_IN_EP_GRP_STATUS_RMASK_VAL 0xffff0003
#define IAXXX_IN_EP_GRP_STATUS_WMASK_VAL 0x00000000
#define IAXXX_IN_EP_GRP_STATUS_RESET_VAL 0x00000000

/*
 * Indicates if the input is in timed-out state or not. The input goes to
 * timed-out state when its source notified it.
 * When the input is in timed-out state, the module does not expect any data
 * to arrive on it. The input moves out of the timed-out state when it
 * receives data.
 * 0 - not timed-out (expecting data)
 * 1 - timed-out (not expecting data)
 */
#define IAXXX_IN_EP_GRP_STATUS_TIMEOUT_MASK 0x00000001
#define IAXXX_IN_EP_GRP_STATUS_TIMEOUT_RESET_VAL 0x0
#define IAXXX_IN_EP_GRP_STATUS_TIMEOUT_POS 0
#define IAXXX_IN_EP_GRP_STATUS_TIMEOUT_SIZE 1

/*
 * Ready-to-receive. Indicates if the module is ready to receive another
 * frame of data on this input
 * 0 - not ready
 * 1 - ready
 */
#define IAXXX_IN_EP_GRP_STATUS_RTR_MASK 0x00000002
#define IAXXX_IN_EP_GRP_STATUS_RTR_RESET_VAL 0x0
#define IAXXX_IN_EP_GRP_STATUS_RTR_POS 1
#define IAXXX_IN_EP_GRP_STATUS_RTR_SIZE 1

/*
 * Indicates number of frame buffers that passed through.
 */
#define IAXXX_IN_EP_GRP_STATUS_COUNTER_MASK 0xffff0000
#define IAXXX_IN_EP_GRP_STATUS_COUNTER_RESET_VAL 0x0
#define IAXXX_IN_EP_GRP_STATUS_COUNTER_POS 16
#define IAXXX_IN_EP_GRP_STATUS_COUNTER_SIZE 16

/* Number of registers in the module */
#define IAXXX_IN_EP_GRP_REG_NUM 2

#endif /* __IAXXX_REGISTER_DEFS_IN_EP_GRP_H__ */
