/*
 * iaxxx-register-defs-script-mgmt.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_SCRIPT_MGMT_H__
#define __IAXXX_REGISTER_DEFS_SCRIPT_MGMT_H__

/*** The base address for this set of registers ***/
#define IAXXX_SCRIPT_MGMT_REGS_ADDR (0x10000000)

/*** SCRIPT_MGMT_SCRIPT_REQ (0x10000000) ***/
/*
 * Request script specific operations.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_ADDR (0x10000000)
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_MASK_VAL 0xffff0007
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_RMASK_VAL 0xffff0007
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_WMASK_VAL 0xffff0007
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_RESET_VAL 0x00000000

/*
 * Host sets to request script unload.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_UNLOAD_MASK 0x00000001
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_UNLOAD_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_UNLOAD_POS 0
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_UNLOAD_SIZE 1

/*
 * Host sets to request script memory allocation.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_LOAD_MASK 0x00000002
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_LOAD_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_LOAD_POS 1
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_LOAD_SIZE 1

/*
 * Host sets to request to execute the script.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_EXECUTE_MASK 0x00000004
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_EXECUTE_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_EXECUTE_POS 2
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_EXECUTE_SIZE 1

/*
 * Host assigned script ID.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_SCRIPT_ID_MASK 0xffff0000
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_SCRIPT_ID_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_SCRIPT_ID_POS 16
#define IAXXX_SCRIPT_MGMT_SCRIPT_REQ_SCRIPT_ID_SIZE 16

/*** SCRIPT_MGMT_SCRIPT_SIZE (0x10000004) ***/
/*
 * Size in bytes of the script.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_ADDR (0x10000004)
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_MASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_WMASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_RESET_VAL 0x00000000

/*
 * Size in bytes of the script.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_REG_MASK 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_REG_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_REG_POS 0
#define IAXXX_SCRIPT_MGMT_SCRIPT_SIZE_REG_SIZE 32

/*** SCRIPT_MGMT_SCRIPT_ADDR (0x10000008) ***/
/*
 * Memory address where the script must be dowloaded.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_ADDR (0x10000008)
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_MASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_WMASK_VAL 0x00000000
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_RESET_VAL 0x00000000

/*
 * Virtual Base address of the package's data memory.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_REG_MASK 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_REG_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_REG_POS 0
#define IAXXX_SCRIPT_MGMT_SCRIPT_ADDR_REG_SIZE 32

/*** SCRIPT_MGMT_SCRIPT_ERROR (0x1000000c) ***/
/*
 * Error encountered during last script operation.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_ADDR (0x1000000c)
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_MASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_RMASK_VAL 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_WMASK_VAL 0x00000000
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_RESET_VAL 0x00000000

/*
 * Error encountered during last script operation.
 */
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_REG_MASK 0xffffffff
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_REG_RESET_VAL 0x0
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_REG_POS 0
#define IAXXX_SCRIPT_MGMT_SCRIPT_ERROR_REG_SIZE 32

/* Number of registers in the module */
#define IAXXX_SCRIPT_MGMT_REG_NUM 4

#endif /* __IAXXX_REGISTER_DEFS_SCRIPT_MGMT_H__ */
