/*
 * iaxxx-register-defs-event-mgmt.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_EVT_MGMT_H__
#define __IAXXX_REGISTER_DEFS_EVT_MGMT_H__

/*** The base address for this set of registers ***/
#define IAXXX_EVT_MGMT_REGS_ADDR (0x0f000000)

/*** EVT_MGMT_EVT (0x0f000000) ***/
/*
 * Request subscription/unsubscription of events.
 */
#define IAXXX_EVT_MGMT_EVT_ADDR (0x0f000000)
#define IAXXX_EVT_MGMT_EVT_MASK_VAL 0x0000001f
#define IAXXX_EVT_MGMT_EVT_RMASK_VAL 0x0000001f
#define IAXXX_EVT_MGMT_EVT_WMASK_VAL 0x0000001f
#define IAXXX_EVT_MGMT_EVT_RESET_VAL 0x00000000

/*
 * Host sets to request event subscription.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_REQ_MASK 0x00000001
#define IAXXX_EVT_MGMT_EVT_SUB_REQ_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SUB_REQ_POS 0
#define IAXXX_EVT_MGMT_EVT_SUB_REQ_SIZE 1
#define IAXXX_EVT_MGMT_EVT_SUB_REQ_DECL 0

/*
 * Host sets to request event trigger.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_EVT_MGMT_EVT_TRIG_REQ_MASK 0x00000002
#define IAXXX_EVT_MGMT_EVT_TRIG_REQ_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_TRIG_REQ_POS 1
#define IAXXX_EVT_MGMT_EVT_TRIG_REQ_SIZE 1
#define IAXXX_EVT_MGMT_EVT_TRIG_REQ_DECL 1

/*
 * Host sets to request event unsubscription.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_EVT_MGMT_EVT_UNSUB_REQ_MASK 0x00000004
#define IAXXX_EVT_MGMT_EVT_UNSUB_REQ_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_UNSUB_REQ_POS 2
#define IAXXX_EVT_MGMT_EVT_UNSUB_REQ_SIZE 1
#define IAXXX_EVT_MGMT_EVT_UNSUB_REQ_DECL 2

/*
 * Host sets to request retrieval of event subscription
 * Requires block update to take effect.
 * Device clears when complete.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_READ_REQ_MASK 0x00000008
#define IAXXX_EVT_MGMT_EVT_SUB_READ_REQ_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SUB_READ_REQ_POS 3
#define IAXXX_EVT_MGMT_EVT_SUB_READ_REQ_SIZE 1
#define IAXXX_EVT_MGMT_EVT_SUB_READ_REQ_DECL 3

/*
 * Host sets to request to reset index for retrieving
 * subscription entries
 */
#define IAXXX_EVT_MGMT_EVT_RESET_RD_IDX_MASK 0x00000010
#define IAXXX_EVT_MGMT_EVT_RESET_RD_IDX_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_RESET_RD_IDX_POS 4
#define IAXXX_EVT_MGMT_EVT_RESET_RD_IDX_SIZE 1
#define IAXXX_EVT_MGMT_EVT_RESET_RD_IDX_DECL 4

/*** EVT_MGMT_EVT_ID (0x0f000004) ***/
/*
 */
#define IAXXX_EVT_MGMT_EVT_ID_ADDR (0x0f000004)
#define IAXXX_EVT_MGMT_EVT_ID_MASK_VAL 0x0000ffff
#define IAXXX_EVT_MGMT_EVT_ID_RMASK_VAL 0x0000ffff
#define IAXXX_EVT_MGMT_EVT_ID_WMASK_VAL 0x0000ffff
#define IAXXX_EVT_MGMT_EVT_ID_RESET_VAL 0x00000000

/*
 * Event ID. Used in subscription and triggering of events.
 */
#define IAXXX_EVT_MGMT_EVT_ID_REG_MASK 0x0000ffff
#define IAXXX_EVT_MGMT_EVT_ID_REG_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_ID_REG_POS 0
#define IAXXX_EVT_MGMT_EVT_ID_REG_SIZE 16
#define IAXXX_EVT_MGMT_EVT_ID_REG_DECL (15 : 0)

/*** EVT_MGMT_EVT_SUB (0x0f000008) ***/
/*
 * The System IDs of the event source and destination.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_ADDR (0x0f000008)
#define IAXXX_EVT_MGMT_EVT_SUB_MASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_RMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_WMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_RESET_VAL 0x00000000

/*
 * System ID of event source.
 * Used in subscription/unsubscription
 * and event triggering.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_SRC_ID_MASK 0x0000ffff
#define IAXXX_EVT_MGMT_EVT_SUB_SRC_ID_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SUB_SRC_ID_POS 0
#define IAXXX_EVT_MGMT_EVT_SUB_SRC_ID_SIZE 16
#define IAXXX_EVT_MGMT_EVT_SUB_SRC_ID_DECL (15 : 0)

/*
 * System ID of event destination.
 * Used in subscription/unsubscription.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_DST_ID_MASK 0xffff0000
#define IAXXX_EVT_MGMT_EVT_SUB_DST_ID_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SUB_DST_ID_POS 16
#define IAXXX_EVT_MGMT_EVT_SUB_DST_ID_SIZE 16
#define IAXXX_EVT_MGMT_EVT_SUB_DST_ID_DECL (31 : 16)

/*** EVT_MGMT_EVT_SUB_DST_OPAQUE (0x0f00000c) ***/
/*
 * Opaque data of event notification.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_ADDR (0x0f00000c)
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_MASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_RMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_WMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_RESET_VAL 0x00000000

/*
 * Opaque data that will be sent to
 * event destination with the event data.
 */
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_REG_MASK 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_REG_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_REG_POS 0
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_REG_SIZE 32
#define IAXXX_EVT_MGMT_EVT_SUB_DST_OPAQUE_REG_DECL (31 : 0)

/*** EVT_MGMT_EVT_NEXT_REQ (0x0f000010) ***/
/*
 * Event notification
 */
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_ADDR (0x0f000010)
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_MASK_VAL 0x00000001
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_RMASK_VAL 0x00000001
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_WMASK_VAL 0x00000001
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_RESET_VAL 0x00000000

/*
 * Host sets to request to get the next event notification.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_NOT_MASK 0x00000001
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_NOT_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_NOT_POS 0
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_NOT_SIZE 1
#define IAXXX_EVT_MGMT_EVT_NEXT_REQ_NOT_DECL 0

/*** EVT_MGMT_EVT_COUNT (0x0f000014) ***/
/*
 * Event count register
 */
#define IAXXX_EVT_MGMT_EVT_COUNT_ADDR (0x0f000014)
#define IAXXX_EVT_MGMT_EVT_COUNT_MASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_COUNT_RMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_COUNT_WMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_COUNT_RESET_VAL 0x00000000

/*
 * Number of pending event notifications.
 */
#define IAXXX_EVT_MGMT_EVT_COUNT_REG_MASK 0xffffffff
#define IAXXX_EVT_MGMT_EVT_COUNT_REG_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_COUNT_REG_POS 0
#define IAXXX_EVT_MGMT_EVT_COUNT_REG_SIZE 32
#define IAXXX_EVT_MGMT_EVT_COUNT_REG_DECL (31 : 0)

/*** EVT_MGMT_EVT_SRC_INFO (0x0f000018) ***/
/*
 * Source of event notification.
 */
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_ADDR (0x0f000018)
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_MASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_RMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_WMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_RESET_VAL 0x00000000

/*
 * System ID of event source.
 */
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_SYS_ID_MASK 0x0000ffff
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_SYS_ID_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_SYS_ID_POS 0
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_SYS_ID_SIZE 16
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_SYS_ID_DECL (15 : 0)

/*
 * Event ID
 */
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_EVT_ID_MASK 0xffff0000
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_EVT_ID_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_EVT_ID_POS 16
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_EVT_ID_SIZE 16
#define IAXXX_EVT_MGMT_EVT_SRC_INFO_EVT_ID_DECL (31 : 16)

/*** EVT_MGMT_EVT_SRC_OPAQUE (0x0f00001c) ***/
/*
 */
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_ADDR (0x0f00001c)
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_MASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_RMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_WMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_RESET_VAL 0x00000000

/*
 * Opaque data that was sent by the event's source.
 */
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_REG_MASK 0xffffffff
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_REG_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_REG_POS 0
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_REG_SIZE 32
#define IAXXX_EVT_MGMT_EVT_SRC_OPAQUE_REG_DECL (31 : 0)

/*** EVT_MGMT_EVT_DST_OPAQUE (0x0f000020) ***/
/*
 * Opaque data that was sent to the event's destination.
 */
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_ADDR (0x0f000020)
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_MASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_RMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_WMASK_VAL 0xffffffff
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_RESET_VAL 0x00000000

/*
 * Opaque data that was sent to the event's destination.
 */
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_REG_MASK 0xffffffff
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_REG_RESET_VAL 0x0
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_REG_POS 0
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_REG_SIZE 32
#define IAXXX_EVT_MGMT_EVT_DST_OPAQUE_REG_DECL (31 : 0)

/* Number of registers in the module */
#define IAXXX_EVT_MGMT_REG_NUM 9

#endif /* __IAXXX_REGISTER_DEFS_EVT_MGMT_H__ */
