/*
 * iaxxx-register-defs-out-endpoint-group.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_OUT_EP_GRP_H__
#define __IAXXX_REGISTER_DEFS_OUT_EP_GRP_H__

/*** The base address for this set of registers ***/
#define IAXXX_OUT_EP_GRP_REGS_ADDR (0x00000000)

/*** OUT_EP_GRP_FORMAT (0x00000000) ***/
/*
 */
#define IAXXX_OUT_EP_GRP_FORMAT_ADDR (0x00000000)
#define IAXXX_OUT_EP_GRP_FORMAT_MASK_VAL 0xffffffff
#define IAXXX_OUT_EP_GRP_FORMAT_RMASK_VAL 0xffffffff
#define IAXXX_OUT_EP_GRP_FORMAT_WMASK_VAL 0xffffffff
#define IAXXX_OUT_EP_GRP_FORMAT_RESET_VAL 0x00000000

/*
 * Encoding of the data contained in the frame buffer coming out of the
 * endpoint
 */
#define IAXXX_OUT_EP_GRP_FORMAT_ENCODING_MASK 0x000000ff
#define IAXXX_OUT_EP_GRP_FORMAT_ENCODING_RESET_VAL 0x0
#define IAXXX_OUT_EP_GRP_FORMAT_ENCODING_POS 0
#define IAXXX_OUT_EP_GRP_FORMAT_ENCODING_SIZE 8

/*
 * Sample rate of the data contained in the frame buffer coming out of the
 * endpoint
 */
#define IAXXX_OUT_EP_GRP_FORMAT_SAMPLE_RATE_MASK 0x0000ff00
#define IAXXX_OUT_EP_GRP_FORMAT_SAMPLE_RATE_RESET_VAL 0x0
#define IAXXX_OUT_EP_GRP_FORMAT_SAMPLE_RATE_POS 8
#define IAXXX_OUT_EP_GRP_FORMAT_SAMPLE_RATE_SIZE 8

/*
 * Number of bytes contained in the frame buffer coming out of the endpoint
 */
#define IAXXX_OUT_EP_GRP_FORMAT_LENGTH_MASK 0xffff0000
#define IAXXX_OUT_EP_GRP_FORMAT_LENGTH_RESET_VAL 0x0
#define IAXXX_OUT_EP_GRP_FORMAT_LENGTH_POS 16
#define IAXXX_OUT_EP_GRP_FORMAT_LENGTH_SIZE 16

/*** OUT_EP_GRP_STATUS (0x00000004) ***/
/*
 */
#define IAXXX_OUT_EP_GRP_STATUS_ADDR (0x00000004)
#define IAXXX_OUT_EP_GRP_STATUS_MASK_VAL 0xffff0003
#define IAXXX_OUT_EP_GRP_STATUS_RMASK_VAL 0xffff0003
#define IAXXX_OUT_EP_GRP_STATUS_WMASK_VAL 0x00000000
#define IAXXX_OUT_EP_GRP_STATUS_RESET_VAL 0x00000000

/*
 * Indicates if the output is in timed-out state or not. The output goes to
 * timed-out state when the routing element does not expect to produce any
 * data on it.
 * The output moves out of the timed-out state when it starts producing data
 * 0 - not timed-out (expecting to produce data)
 * 1 - timed-out (not expecting to produce data)
 */
#define IAXXX_OUT_EP_GRP_STATUS_TIMEOUT_MASK 0x00000001
#define IAXXX_OUT_EP_GRP_STATUS_TIMEOUT_RESET_VAL 0x0
#define IAXXX_OUT_EP_GRP_STATUS_TIMEOUT_POS 0
#define IAXXX_OUT_EP_GRP_STATUS_TIMEOUT_SIZE 1

/*
 * Clear-to-send. Indicates if the endpoint is allowed to send another frame
 * bufffer to its destination
 * 0 - not allowed to send
 * 1 - allowed to send
 */
#define IAXXX_OUT_EP_GRP_STATUS_CTS_MASK 0x00000002
#define IAXXX_OUT_EP_GRP_STATUS_CTS_RESET_VAL 0x0
#define IAXXX_OUT_EP_GRP_STATUS_CTS_POS 1
#define IAXXX_OUT_EP_GRP_STATUS_CTS_SIZE 1

/*
 * Indicates number of frame buffers that passed through.
 */
#define IAXXX_OUT_EP_GRP_STATUS_COUNTER_MASK 0xffff0000
#define IAXXX_OUT_EP_GRP_STATUS_COUNTER_RESET_VAL 0x0
#define IAXXX_OUT_EP_GRP_STATUS_COUNTER_POS 16
#define IAXXX_OUT_EP_GRP_STATUS_COUNTER_SIZE 16

/* Number of registers in the module */
#define IAXXX_OUT_EP_GRP_REG_NUM 2

#endif /* __IAXXX_REGISTER_DEFS_OUT_EP_GRP_H__ */
