/*
 * iaxxx-register-defs-channel-header.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_CH_HDR_H__
#define __IAXXX_REGISTER_DEFS_CH_HDR_H__

/*** The base address for this set of registers ***/
#define IAXXX_CH_HDR_REGS_ADDR (0x01000000)

/*** CH_HDR_CH_CNT (0x01000000) ***/
/*
 * Number of channel groups supported in the channel block.(Not active
 * channel count)
 */
#define IAXXX_CH_HDR_CH_CNT_ADDR (0x01000000)
#define IAXXX_CH_HDR_CH_CNT_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_WMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_RESET_VAL 0x00000000

/*
 * Number of channel groups supported in the channel block.(Not active
 * channel count)
 */
#define IAXXX_CH_HDR_CH_CNT_REG_MASK 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_CNT_REG_POS 0
#define IAXXX_CH_HDR_CH_CNT_REG_SIZE 32

/*** CH_HDR_CH_ST (0x01000004) ***/
/*
 * Channel Enabled/Disabled.
 */
#define IAXXX_CH_HDR_CH_ST_ADDR (0x01000004)
#define IAXXX_CH_HDR_CH_ST_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_ST_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_ST_WMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_ST_RESET_VAL 0x00000000

/*
 * Channel 0 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_0_REG_MASK 0x00000001
#define IAXXX_CH_HDR_CH_ST_0_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_0_REG_POS 0
#define IAXXX_CH_HDR_CH_ST_0_REG_SIZE 1

/*
 * Channel 1 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_1_REG_MASK 0x00000002
#define IAXXX_CH_HDR_CH_ST_1_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_1_REG_POS 1
#define IAXXX_CH_HDR_CH_ST_1_REG_SIZE 1

/*
 * Channel 2 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_2_REG_MASK 0x00000004
#define IAXXX_CH_HDR_CH_ST_2_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_2_REG_POS 2
#define IAXXX_CH_HDR_CH_ST_2_REG_SIZE 1

/*
 * Channel 3 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_3_REG_MASK 0x00000008
#define IAXXX_CH_HDR_CH_ST_3_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_3_REG_POS 3
#define IAXXX_CH_HDR_CH_ST_3_REG_SIZE 1

/*
 * Channel 4 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_4_REG_MASK 0x00000010
#define IAXXX_CH_HDR_CH_ST_4_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_4_REG_POS 4
#define IAXXX_CH_HDR_CH_ST_4_REG_SIZE 1

/*
 * Channel 5 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_5_REG_MASK 0x00000020
#define IAXXX_CH_HDR_CH_ST_5_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_5_REG_POS 5
#define IAXXX_CH_HDR_CH_ST_5_REG_SIZE 1

/*
 * Channel 6 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_6_REG_MASK 0x00000040
#define IAXXX_CH_HDR_CH_ST_6_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_6_REG_POS 6
#define IAXXX_CH_HDR_CH_ST_6_REG_SIZE 1

/*
 * Channel 7 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_7_REG_MASK 0x00000080
#define IAXXX_CH_HDR_CH_ST_7_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_7_REG_POS 7
#define IAXXX_CH_HDR_CH_ST_7_REG_SIZE 1

/*
 * Channel 8 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_8_REG_MASK 0x00000100
#define IAXXX_CH_HDR_CH_ST_8_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_8_REG_POS 8
#define IAXXX_CH_HDR_CH_ST_8_REG_SIZE 1

/*
 * Channel 9 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_9_REG_MASK 0x00000200
#define IAXXX_CH_HDR_CH_ST_9_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_9_REG_POS 9
#define IAXXX_CH_HDR_CH_ST_9_REG_SIZE 1

/*
 * Channel 10 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_10_REG_MASK 0x00000400
#define IAXXX_CH_HDR_CH_ST_10_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_10_REG_POS 10
#define IAXXX_CH_HDR_CH_ST_10_REG_SIZE 1

/*
 * Channel 11 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_11_REG_MASK 0x00000800
#define IAXXX_CH_HDR_CH_ST_11_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_11_REG_POS 11
#define IAXXX_CH_HDR_CH_ST_11_REG_SIZE 1

/*
 * Channel 12 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_12_REG_MASK 0x00001000
#define IAXXX_CH_HDR_CH_ST_12_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_12_REG_POS 12
#define IAXXX_CH_HDR_CH_ST_12_REG_SIZE 1

/*
 * Channel 13 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_13_REG_MASK 0x00002000
#define IAXXX_CH_HDR_CH_ST_13_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_13_REG_POS 13
#define IAXXX_CH_HDR_CH_ST_13_REG_SIZE 1

/*
 * Channel 14 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_14_REG_MASK 0x00004000
#define IAXXX_CH_HDR_CH_ST_14_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_14_REG_POS 14
#define IAXXX_CH_HDR_CH_ST_14_REG_SIZE 1

/*
 * Channel 15 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_15_REG_MASK 0x00008000
#define IAXXX_CH_HDR_CH_ST_15_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_15_REG_POS 15
#define IAXXX_CH_HDR_CH_ST_15_REG_SIZE 1

/*
 * Channel 16 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_16_REG_MASK 0x00010000
#define IAXXX_CH_HDR_CH_ST_16_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_16_REG_POS 16
#define IAXXX_CH_HDR_CH_ST_16_REG_SIZE 1

/*
 * Channel 17 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_17_REG_MASK 0x00020000
#define IAXXX_CH_HDR_CH_ST_17_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_17_REG_POS 17
#define IAXXX_CH_HDR_CH_ST_17_REG_SIZE 1

/*
 * Channel 18 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_18_REG_MASK 0x00040000
#define IAXXX_CH_HDR_CH_ST_18_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_18_REG_POS 18
#define IAXXX_CH_HDR_CH_ST_18_REG_SIZE 1

/*
 * Channel 19 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_19_REG_MASK 0x00080000
#define IAXXX_CH_HDR_CH_ST_19_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_19_REG_POS 19
#define IAXXX_CH_HDR_CH_ST_19_REG_SIZE 1

/*
 * Channel 20 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_20_REG_MASK 0x00100000
#define IAXXX_CH_HDR_CH_ST_20_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_20_REG_POS 20
#define IAXXX_CH_HDR_CH_ST_20_REG_SIZE 1

/*
 * Channel 21 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_21_REG_MASK 0x00200000
#define IAXXX_CH_HDR_CH_ST_21_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_21_REG_POS 21
#define IAXXX_CH_HDR_CH_ST_21_REG_SIZE 1

/*
 * Channel 22 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_22_REG_MASK 0x00400000
#define IAXXX_CH_HDR_CH_ST_22_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_22_REG_POS 22
#define IAXXX_CH_HDR_CH_ST_22_REG_SIZE 1

/*
 * Channel 23 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_23_REG_MASK 0x00800000
#define IAXXX_CH_HDR_CH_ST_23_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_23_REG_POS 23
#define IAXXX_CH_HDR_CH_ST_23_REG_SIZE 1

/*
 * Channel 24 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_24_REG_MASK 0x01000000
#define IAXXX_CH_HDR_CH_ST_24_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_24_REG_POS 24
#define IAXXX_CH_HDR_CH_ST_24_REG_SIZE 1

/*
 * Channel 25 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_25_REG_MASK 0x02000000
#define IAXXX_CH_HDR_CH_ST_25_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_25_REG_POS 25
#define IAXXX_CH_HDR_CH_ST_25_REG_SIZE 1

/*
 * Channel 26 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_26_REG_MASK 0x04000000
#define IAXXX_CH_HDR_CH_ST_26_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_26_REG_POS 26
#define IAXXX_CH_HDR_CH_ST_26_REG_SIZE 1

/*
 * Channel 27 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_27_REG_MASK 0x08000000
#define IAXXX_CH_HDR_CH_ST_27_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_27_REG_POS 27
#define IAXXX_CH_HDR_CH_ST_27_REG_SIZE 1

/*
 * Channel 28 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_28_REG_MASK 0x10000000
#define IAXXX_CH_HDR_CH_ST_28_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_28_REG_POS 28
#define IAXXX_CH_HDR_CH_ST_28_REG_SIZE 1

/*
 * Channel 29 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_29_REG_MASK 0x20000000
#define IAXXX_CH_HDR_CH_ST_29_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_29_REG_POS 29
#define IAXXX_CH_HDR_CH_ST_29_REG_SIZE 1

/*
 * Channel 30 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_30_REG_MASK 0x40000000
#define IAXXX_CH_HDR_CH_ST_30_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_30_REG_POS 30
#define IAXXX_CH_HDR_CH_ST_30_REG_SIZE 1

/*
 * Channel 31 status
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_ST_31_REG_MASK 0x80000000
#define IAXXX_CH_HDR_CH_ST_31_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_ST_31_REG_POS 31
#define IAXXX_CH_HDR_CH_ST_31_REG_SIZE 1

/*** CH_HDR_CH_DIR (0x01000008) ***/
/*
 * Channel Direction
 */
#define IAXXX_CH_HDR_CH_DIR_ADDR (0x01000008)
#define IAXXX_CH_HDR_CH_DIR_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_DIR_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_DIR_WMASK_VAL 0x00000000
#define IAXXX_CH_HDR_CH_DIR_RESET_VAL 0x00000000

/*
 * Channel 0 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_0_REG_MASK 0x00000001
#define IAXXX_CH_HDR_CH_DIR_0_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_0_REG_POS 0
#define IAXXX_CH_HDR_CH_DIR_0_REG_SIZE 1

/*
 * Channel 1 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_1_REG_MASK 0x00000002
#define IAXXX_CH_HDR_CH_DIR_1_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_1_REG_POS 1
#define IAXXX_CH_HDR_CH_DIR_1_REG_SIZE 1

/*
 * Channel 2 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_2_REG_MASK 0x00000004
#define IAXXX_CH_HDR_CH_DIR_2_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_2_REG_POS 2
#define IAXXX_CH_HDR_CH_DIR_2_REG_SIZE 1

/*
 * Channel 3 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_3_REG_MASK 0x00000008
#define IAXXX_CH_HDR_CH_DIR_3_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_3_REG_POS 3
#define IAXXX_CH_HDR_CH_DIR_3_REG_SIZE 1

/*
 * Channel 4 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_4_REG_MASK 0x00000010
#define IAXXX_CH_HDR_CH_DIR_4_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_4_REG_POS 4
#define IAXXX_CH_HDR_CH_DIR_4_REG_SIZE 1

/*
 * Channel 5 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_5_REG_MASK 0x00000020
#define IAXXX_CH_HDR_CH_DIR_5_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_5_REG_POS 5
#define IAXXX_CH_HDR_CH_DIR_5_REG_SIZE 1

/*
 * Channel 6 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_6_REG_MASK 0x00000040
#define IAXXX_CH_HDR_CH_DIR_6_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_6_REG_POS 6
#define IAXXX_CH_HDR_CH_DIR_6_REG_SIZE 1

/*
 * Channel 7 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_7_REG_MASK 0x00000080
#define IAXXX_CH_HDR_CH_DIR_7_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_7_REG_POS 7
#define IAXXX_CH_HDR_CH_DIR_7_REG_SIZE 1

/*
 * Channel 8 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_8_REG_MASK 0x00000100
#define IAXXX_CH_HDR_CH_DIR_8_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_8_REG_POS 8
#define IAXXX_CH_HDR_CH_DIR_8_REG_SIZE 1

/*
 * Channel 9 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_9_REG_MASK 0x00000200
#define IAXXX_CH_HDR_CH_DIR_9_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_9_REG_POS 9
#define IAXXX_CH_HDR_CH_DIR_9_REG_SIZE 1

/*
 * Channel 10 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_10_REG_MASK 0x00000400
#define IAXXX_CH_HDR_CH_DIR_10_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_10_REG_POS 10
#define IAXXX_CH_HDR_CH_DIR_10_REG_SIZE 1

/*
 * Channel 11 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_11_REG_MASK 0x00000800
#define IAXXX_CH_HDR_CH_DIR_11_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_11_REG_POS 11
#define IAXXX_CH_HDR_CH_DIR_11_REG_SIZE 1

/*
 * Channel 12 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_12_REG_MASK 0x00001000
#define IAXXX_CH_HDR_CH_DIR_12_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_12_REG_POS 12
#define IAXXX_CH_HDR_CH_DIR_12_REG_SIZE 1

/*
 * Channel 13 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_13_REG_MASK 0x00002000
#define IAXXX_CH_HDR_CH_DIR_13_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_13_REG_POS 13
#define IAXXX_CH_HDR_CH_DIR_13_REG_SIZE 1

/*
 * Channel 14 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_14_REG_MASK 0x00004000
#define IAXXX_CH_HDR_CH_DIR_14_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_14_REG_POS 14
#define IAXXX_CH_HDR_CH_DIR_14_REG_SIZE 1

/*
 * Channel 15 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_15_REG_MASK 0x00008000
#define IAXXX_CH_HDR_CH_DIR_15_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_15_REG_POS 15
#define IAXXX_CH_HDR_CH_DIR_15_REG_SIZE 1

/*
 * Channel 16 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_16_REG_MASK 0x00010000
#define IAXXX_CH_HDR_CH_DIR_16_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_16_REG_POS 16
#define IAXXX_CH_HDR_CH_DIR_16_REG_SIZE 1

/*
 * Channel 17 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_17_REG_MASK 0x00020000
#define IAXXX_CH_HDR_CH_DIR_17_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_17_REG_POS 17
#define IAXXX_CH_HDR_CH_DIR_17_REG_SIZE 1

/*
 * Channel 18 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_18_REG_MASK 0x00040000
#define IAXXX_CH_HDR_CH_DIR_18_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_18_REG_POS 18
#define IAXXX_CH_HDR_CH_DIR_18_REG_SIZE 1

/*
 * Channel 19 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_19_REG_MASK 0x00080000
#define IAXXX_CH_HDR_CH_DIR_19_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_19_REG_POS 19
#define IAXXX_CH_HDR_CH_DIR_19_REG_SIZE 1

/*
 * Channel 20 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_20_REG_MASK 0x00100000
#define IAXXX_CH_HDR_CH_DIR_20_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_20_REG_POS 20
#define IAXXX_CH_HDR_CH_DIR_20_REG_SIZE 1

/*
 * Channel 21 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_21_REG_MASK 0x00200000
#define IAXXX_CH_HDR_CH_DIR_21_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_21_REG_POS 21
#define IAXXX_CH_HDR_CH_DIR_21_REG_SIZE 1

/*
 * Channel 22 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_22_REG_MASK 0x00400000
#define IAXXX_CH_HDR_CH_DIR_22_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_22_REG_POS 22
#define IAXXX_CH_HDR_CH_DIR_22_REG_SIZE 1

/*
 * Channel 23 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_23_REG_MASK 0x00800000
#define IAXXX_CH_HDR_CH_DIR_23_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_23_REG_POS 23
#define IAXXX_CH_HDR_CH_DIR_23_REG_SIZE 1

/*
 * Channel 24 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_24_REG_MASK 0x01000000
#define IAXXX_CH_HDR_CH_DIR_24_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_24_REG_POS 24
#define IAXXX_CH_HDR_CH_DIR_24_REG_SIZE 1

/*
 * Channel 25 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_25_REG_MASK 0x02000000
#define IAXXX_CH_HDR_CH_DIR_25_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_25_REG_POS 25
#define IAXXX_CH_HDR_CH_DIR_25_REG_SIZE 1

/*
 * Channel 26 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_26_REG_MASK 0x04000000
#define IAXXX_CH_HDR_CH_DIR_26_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_26_REG_POS 26
#define IAXXX_CH_HDR_CH_DIR_26_REG_SIZE 1

/*
 * Channel 27 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_27_REG_MASK 0x08000000
#define IAXXX_CH_HDR_CH_DIR_27_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_27_REG_POS 27
#define IAXXX_CH_HDR_CH_DIR_27_REG_SIZE 1

/*
 * Channel 28 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_28_REG_MASK 0x10000000
#define IAXXX_CH_HDR_CH_DIR_28_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_28_REG_POS 28
#define IAXXX_CH_HDR_CH_DIR_28_REG_SIZE 1

/*
 * Channel 29 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_29_REG_MASK 0x20000000
#define IAXXX_CH_HDR_CH_DIR_29_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_29_REG_POS 29
#define IAXXX_CH_HDR_CH_DIR_29_REG_SIZE 1

/*
 * Channel 30 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_30_REG_MASK 0x40000000
#define IAXXX_CH_HDR_CH_DIR_30_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_30_REG_POS 30
#define IAXXX_CH_HDR_CH_DIR_30_REG_SIZE 1

/*
 * Channel 31 direction
 * 0 - input
 * 1 - output
 */
#define IAXXX_CH_HDR_CH_DIR_31_REG_MASK 0x80000000
#define IAXXX_CH_HDR_CH_DIR_31_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_DIR_31_REG_POS 31
#define IAXXX_CH_HDR_CH_DIR_31_REG_SIZE 1

/*** CH_HDR_CH_GAIN (0x0100000c) ***/
/*
 * Trigger gain update for channels. Set by host, cleared by device.
 */
#define IAXXX_CH_HDR_CH_GAIN_ADDR (0x0100000c)
#define IAXXX_CH_HDR_CH_GAIN_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_GAIN_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_GAIN_WMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_GAIN_RESET_VAL 0x00000000

/*
 * Update gain for channel 0
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_0_REG_MASK 0x00000001
#define IAXXX_CH_HDR_CH_GAIN_0_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_0_REG_POS 0
#define IAXXX_CH_HDR_CH_GAIN_0_REG_SIZE 1

/*
 * Update gain for channel 1
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_1_REG_MASK 0x00000002
#define IAXXX_CH_HDR_CH_GAIN_1_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_1_REG_POS 1
#define IAXXX_CH_HDR_CH_GAIN_1_REG_SIZE 1

/*
 * Update gain for channel 2
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_2_REG_MASK 0x00000004
#define IAXXX_CH_HDR_CH_GAIN_2_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_2_REG_POS 2
#define IAXXX_CH_HDR_CH_GAIN_2_REG_SIZE 1

/*
 * Update gain for channel 3
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_3_REG_MASK 0x00000008
#define IAXXX_CH_HDR_CH_GAIN_3_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_3_REG_POS 3
#define IAXXX_CH_HDR_CH_GAIN_3_REG_SIZE 1

/*
 * Update gain for channel 4
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_4_REG_MASK 0x00000010
#define IAXXX_CH_HDR_CH_GAIN_4_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_4_REG_POS 4
#define IAXXX_CH_HDR_CH_GAIN_4_REG_SIZE 1

/*
 * Update gain for channel 5
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_5_REG_MASK 0x00000020
#define IAXXX_CH_HDR_CH_GAIN_5_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_5_REG_POS 5
#define IAXXX_CH_HDR_CH_GAIN_5_REG_SIZE 1

/*
 * Update gain for channel 6
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_6_REG_MASK 0x00000040
#define IAXXX_CH_HDR_CH_GAIN_6_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_6_REG_POS 6
#define IAXXX_CH_HDR_CH_GAIN_6_REG_SIZE 1

/*
 * Update gain for channel 7
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_7_REG_MASK 0x00000080
#define IAXXX_CH_HDR_CH_GAIN_7_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_7_REG_POS 7
#define IAXXX_CH_HDR_CH_GAIN_7_REG_SIZE 1

/*
 * Update gain for channel 8
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_8_REG_MASK 0x00000100
#define IAXXX_CH_HDR_CH_GAIN_8_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_8_REG_POS 8
#define IAXXX_CH_HDR_CH_GAIN_8_REG_SIZE 1

/*
 * Update gain for channel 9
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_9_REG_MASK 0x00000200
#define IAXXX_CH_HDR_CH_GAIN_9_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_9_REG_POS 9
#define IAXXX_CH_HDR_CH_GAIN_9_REG_SIZE 1

/*
 * Update gain for channel 10
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_10_REG_MASK 0x00000400
#define IAXXX_CH_HDR_CH_GAIN_10_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_10_REG_POS 10
#define IAXXX_CH_HDR_CH_GAIN_10_REG_SIZE 1

/*
 * Update gain for channel 11
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_11_REG_MASK 0x00000800
#define IAXXX_CH_HDR_CH_GAIN_11_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_11_REG_POS 11
#define IAXXX_CH_HDR_CH_GAIN_11_REG_SIZE 1

/*
 * Update gain for channel 12
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_12_REG_MASK 0x00001000
#define IAXXX_CH_HDR_CH_GAIN_12_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_12_REG_POS 12
#define IAXXX_CH_HDR_CH_GAIN_12_REG_SIZE 1

/*
 * Update gain for channel 13
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_13_REG_MASK 0x00002000
#define IAXXX_CH_HDR_CH_GAIN_13_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_13_REG_POS 13
#define IAXXX_CH_HDR_CH_GAIN_13_REG_SIZE 1

/*
 * Update gain for channel 14
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_14_REG_MASK 0x00004000
#define IAXXX_CH_HDR_CH_GAIN_14_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_14_REG_POS 14
#define IAXXX_CH_HDR_CH_GAIN_14_REG_SIZE 1

/*
 * Update gain for channel 15
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_15_REG_MASK 0x00008000
#define IAXXX_CH_HDR_CH_GAIN_15_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_15_REG_POS 15
#define IAXXX_CH_HDR_CH_GAIN_15_REG_SIZE 1

/*
 * Update gain for channel 16
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_16_REG_MASK 0x00010000
#define IAXXX_CH_HDR_CH_GAIN_16_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_16_REG_POS 16
#define IAXXX_CH_HDR_CH_GAIN_16_REG_SIZE 1

/*
 * Update gain for channel 17
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_17_REG_MASK 0x00020000
#define IAXXX_CH_HDR_CH_GAIN_17_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_17_REG_POS 17
#define IAXXX_CH_HDR_CH_GAIN_17_REG_SIZE 1

/*
 * Update gain for channel 18
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_18_REG_MASK 0x00040000
#define IAXXX_CH_HDR_CH_GAIN_18_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_18_REG_POS 18
#define IAXXX_CH_HDR_CH_GAIN_18_REG_SIZE 1

/*
 * Update gain for channel 19
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_19_REG_MASK 0x00080000
#define IAXXX_CH_HDR_CH_GAIN_19_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_19_REG_POS 19
#define IAXXX_CH_HDR_CH_GAIN_19_REG_SIZE 1

/*
 * Update gain for channel 20
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_20_REG_MASK 0x00100000
#define IAXXX_CH_HDR_CH_GAIN_20_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_20_REG_POS 20
#define IAXXX_CH_HDR_CH_GAIN_20_REG_SIZE 1

/*
 * Update gain for channel 21
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_21_REG_MASK 0x00200000
#define IAXXX_CH_HDR_CH_GAIN_21_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_21_REG_POS 21
#define IAXXX_CH_HDR_CH_GAIN_21_REG_SIZE 1

/*
 * Update gain for channel 22
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_22_REG_MASK 0x00400000
#define IAXXX_CH_HDR_CH_GAIN_22_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_22_REG_POS 22
#define IAXXX_CH_HDR_CH_GAIN_22_REG_SIZE 1

/*
 * Update gain for channel 23
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_23_REG_MASK 0x00800000
#define IAXXX_CH_HDR_CH_GAIN_23_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_23_REG_POS 23
#define IAXXX_CH_HDR_CH_GAIN_23_REG_SIZE 1

/*
 * Update gain for channel 24
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_24_REG_MASK 0x01000000
#define IAXXX_CH_HDR_CH_GAIN_24_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_24_REG_POS 24
#define IAXXX_CH_HDR_CH_GAIN_24_REG_SIZE 1

/*
 * Update gain for channel 25
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_25_REG_MASK 0x02000000
#define IAXXX_CH_HDR_CH_GAIN_25_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_25_REG_POS 25
#define IAXXX_CH_HDR_CH_GAIN_25_REG_SIZE 1

/*
 * Update gain for channel 26
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_26_REG_MASK 0x04000000
#define IAXXX_CH_HDR_CH_GAIN_26_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_26_REG_POS 26
#define IAXXX_CH_HDR_CH_GAIN_26_REG_SIZE 1

/*
 * Update gain for channel 27
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_27_REG_MASK 0x08000000
#define IAXXX_CH_HDR_CH_GAIN_27_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_27_REG_POS 27
#define IAXXX_CH_HDR_CH_GAIN_27_REG_SIZE 1

/*
 * Update gain for channel 28
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_28_REG_MASK 0x10000000
#define IAXXX_CH_HDR_CH_GAIN_28_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_28_REG_POS 28
#define IAXXX_CH_HDR_CH_GAIN_28_REG_SIZE 1

/*
 * Update gain for channel 29
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_29_REG_MASK 0x20000000
#define IAXXX_CH_HDR_CH_GAIN_29_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_29_REG_POS 29
#define IAXXX_CH_HDR_CH_GAIN_29_REG_SIZE 1

/*
 * Update gain for channel 30
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_30_REG_MASK 0x40000000
#define IAXXX_CH_HDR_CH_GAIN_30_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_30_REG_POS 30
#define IAXXX_CH_HDR_CH_GAIN_30_REG_SIZE 1

/*
 * Update gain for channel 31
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_31_REG_MASK 0x80000000
#define IAXXX_CH_HDR_CH_GAIN_31_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_31_REG_POS 31
#define IAXXX_CH_HDR_CH_GAIN_31_REG_SIZE 1

/* Number of registers in the module */
#define IAXXX_CH_HDR_REG_NUM 4

#endif /* __IAXXX_REGISTER_DEFS_CH_HDR_H__ */
