/*
 * iaxxx-register-defs-pkg-mgmt.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_PKG_MGMT_H__
#define __IAXXX_REGISTER_DEFS_PKG_MGMT_H__

/*** The base address for this set of registers ***/
#define IAXXX_PKG_MGMT_REGS_ADDR (0x04000000)

/*** PKG_MGMT_PKG_REQ (0x04000000) ***/
/*
 * Request package specific operations.
 */
#define IAXXX_PKG_MGMT_PKG_REQ_ADDR (0x04000000)
#define IAXXX_PKG_MGMT_PKG_REQ_MASK_VAL 0x00000007
#define IAXXX_PKG_MGMT_PKG_REQ_RMASK_VAL 0x00000007
#define IAXXX_PKG_MGMT_PKG_REQ_WMASK_VAL 0x00000007
#define IAXXX_PKG_MGMT_PKG_REQ_RESET_VAL 0x00000000

/*
 * Host sets to request package registration.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_PKG_MGMT_PKG_REQ_REGISTER_MASK 0x00000001
#define IAXXX_PKG_MGMT_PKG_REQ_REGISTER_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_REQ_REGISTER_POS 0
#define IAXXX_PKG_MGMT_PKG_REQ_REGISTER_SIZE 1

/*
 * Host sets to request package unload.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_PKG_MGMT_PKG_REQ_UNLOAD_MASK 0x00000002
#define IAXXX_PKG_MGMT_PKG_REQ_UNLOAD_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_REQ_UNLOAD_POS 1
#define IAXXX_PKG_MGMT_PKG_REQ_UNLOAD_SIZE 1

/*
 * Host sets to request package memory allocation.
 * Requires block update to take effect.
 * Device clears when operation is complete.
 */
#define IAXXX_PKG_MGMT_PKG_REQ_LOAD_MASK 0x00000004
#define IAXXX_PKG_MGMT_PKG_REQ_LOAD_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_REQ_LOAD_POS 2
#define IAXXX_PKG_MGMT_PKG_REQ_LOAD_SIZE 1

/*** PKG_MGMT_PKG_PROC_ID (0x04000004) ***/
/*
 * Package and Proc ID.
 */
#define IAXXX_PKG_MGMT_PKG_PROC_ID_ADDR (0x04000004)
#define IAXXX_PKG_MGMT_PKG_PROC_ID_MASK_VAL 0x0000ffff
#define IAXXX_PKG_MGMT_PKG_PROC_ID_RMASK_VAL 0x0000ffff
#define IAXXX_PKG_MGMT_PKG_PROC_ID_WMASK_VAL 0x0000ffff
#define IAXXX_PKG_MGMT_PKG_PROC_ID_RESET_VAL 0x00000000

/*
 * Host assigned package ID.
 */
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PACKAGE_ID_MASK 0x00000fff
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PACKAGE_ID_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PACKAGE_ID_POS 0
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PACKAGE_ID_SIZE 12

/*
 * ID of the processor that the package is running on.
 */
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PROC_ID_MASK 0x0000f000
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PROC_ID_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PROC_ID_POS 12
#define IAXXX_PKG_MGMT_PKG_PROC_ID_PROC_ID_SIZE 4

/*** PKG_MGMT_PKG_INFO (0x04000008) ***/
/*
 * Package info.
 */
#define IAXXX_PKG_MGMT_PKG_INFO_ADDR (0x04000008)
#define IAXXX_PKG_MGMT_PKG_INFO_MASK_VAL 0x000000ff
#define IAXXX_PKG_MGMT_PKG_INFO_RMASK_VAL 0x000000ff
#define IAXXX_PKG_MGMT_PKG_INFO_WMASK_VAL 0x000000ff
#define IAXXX_PKG_MGMT_PKG_INFO_RESET_VAL 0x00000000

/*
 * ID of ISA architecture that the package was built for.
 */
#define IAXXX_PKG_MGMT_PKG_INFO_CORE_ID_MASK 0x0000000f
#define IAXXX_PKG_MGMT_PKG_INFO_CORE_ID_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_INFO_CORE_ID_POS 0
#define IAXXX_PKG_MGMT_PKG_INFO_CORE_ID_SIZE 4

/*
 * Vendor ID:
 * 0: Audience/Knowles
 * 1: Other.
 */
#define IAXXX_PKG_MGMT_PKG_INFO_VENDOR_ID_MASK 0x000000f0
#define IAXXX_PKG_MGMT_PKG_INFO_VENDOR_ID_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_INFO_VENDOR_ID_POS 4
#define IAXXX_PKG_MGMT_PKG_INFO_VENDOR_ID_SIZE 4

/*** PKG_MGMT_PKG_IADDR_P (0x0400000c) ***/
/*
 * Physical Base address of the package's instruction memory.
 */
#define IAXXX_PKG_MGMT_PKG_IADDR_P_ADDR (0x0400000c)
#define IAXXX_PKG_MGMT_PKG_IADDR_P_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_P_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_P_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_P_RESET_VAL 0x00000000

/*
 * Physical Base address of the package's instruction memory.
 */
#define IAXXX_PKG_MGMT_PKG_IADDR_P_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_P_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_IADDR_P_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_IADDR_P_REG_SIZE 32

/*** PKG_MGMT_PKG_IADDR_V (0x04000010) ***/
/*
 * Virtual Base address of the package's instruction memory.
 */
#define IAXXX_PKG_MGMT_PKG_IADDR_V_ADDR (0x04000010)
#define IAXXX_PKG_MGMT_PKG_IADDR_V_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_V_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_V_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_V_RESET_VAL 0x00000000

/*
 * Virtual Base address of the package's instruction memory.
 */
#define IAXXX_PKG_MGMT_PKG_IADDR_V_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_IADDR_V_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_IADDR_V_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_IADDR_V_REG_SIZE 32

/*** PKG_MGMT_PKG_ISIZE (0x04000014) ***/
/*
 * Size in bytes of the package's instruction memory.
 */
#define IAXXX_PKG_MGMT_PKG_ISIZE_ADDR (0x04000014)
#define IAXXX_PKG_MGMT_PKG_ISIZE_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ISIZE_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ISIZE_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ISIZE_RESET_VAL 0x00000000

/*
 * Size in bytes of the package's instruction memory.
 */
#define IAXXX_PKG_MGMT_PKG_ISIZE_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ISIZE_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_ISIZE_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_ISIZE_REG_SIZE 32

/*** PKG_MGMT_PKG_DADDR_P (0x04000018) ***/
/*
 * Physical Base address of the package's data memory.
 */
#define IAXXX_PKG_MGMT_PKG_DADDR_P_ADDR (0x04000018)
#define IAXXX_PKG_MGMT_PKG_DADDR_P_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_P_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_P_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_P_RESET_VAL 0x00000000

/*
 * Physical Base address of the package's data memory.
 */
#define IAXXX_PKG_MGMT_PKG_DADDR_P_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_P_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_DADDR_P_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_DADDR_P_REG_SIZE 32

/*** PKG_MGMT_PKG_DADDR_V (0x0400001c) ***/
/*
 * Virtual Base address of the package's data memory.
 */
#define IAXXX_PKG_MGMT_PKG_DADDR_V_ADDR (0x0400001c)
#define IAXXX_PKG_MGMT_PKG_DADDR_V_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_V_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_V_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_V_RESET_VAL 0x00000000

/*
 * Virtual Base address of the package's data memory.
 */
#define IAXXX_PKG_MGMT_PKG_DADDR_V_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DADDR_V_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_DADDR_V_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_DADDR_V_REG_SIZE 32

/*** PKG_MGMT_PKG_DSIZE (0x04000020) ***/
/*
 * Size in bytes of the package's data memory.
 */
#define IAXXX_PKG_MGMT_PKG_DSIZE_ADDR (0x04000020)
#define IAXXX_PKG_MGMT_PKG_DSIZE_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DSIZE_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DSIZE_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DSIZE_RESET_VAL 0x00000000

/*
 * Size in bytes of the package's data memory.
 */
#define IAXXX_PKG_MGMT_PKG_DSIZE_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_DSIZE_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_DSIZE_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_DSIZE_REG_SIZE 32

/*** PKG_MGMT_PKG_ENTRY (0x04000024) ***/
/*
 * Address of the entry point to the package.
 */
#define IAXXX_PKG_MGMT_PKG_ENTRY_ADDR (0x04000024)
#define IAXXX_PKG_MGMT_PKG_ENTRY_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ENTRY_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ENTRY_WMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ENTRY_RESET_VAL 0x00000000

/*
 * Address of the entry point to the package.
 */
#define IAXXX_PKG_MGMT_PKG_ENTRY_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ENTRY_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_ENTRY_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_ENTRY_REG_SIZE 32

/*** PKG_MGMT_PKG_ERROR (0x04000028) ***/
/*
 * Error encountered during last operation.
 */
#define IAXXX_PKG_MGMT_PKG_ERROR_ADDR (0x04000028)
#define IAXXX_PKG_MGMT_PKG_ERROR_MASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ERROR_RMASK_VAL 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ERROR_WMASK_VAL 0x00000000
#define IAXXX_PKG_MGMT_PKG_ERROR_RESET_VAL 0x00000000

/*
 * Error encountered during last operation.
 */
#define IAXXX_PKG_MGMT_PKG_ERROR_REG_MASK 0xffffffff
#define IAXXX_PKG_MGMT_PKG_ERROR_REG_RESET_VAL 0x0
#define IAXXX_PKG_MGMT_PKG_ERROR_REG_POS 0
#define IAXXX_PKG_MGMT_PKG_ERROR_REG_SIZE 32

/* Number of registers in the module */
#define IAXXX_PKG_MGMT_REG_NUM 11

#endif /* __IAXXX_REGISTER_DEFS_PKG_MGMT_H__ */
