/*
 * iaxxx-register-defs-sidetone-hdr.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/
/*
 *
 * AUTO-GENERATED BY gen_reg_header. DO NOT EDIT.
 *
 * sw_register_defs_SIDETONE_HDR.h
 *
 * This file contains definitions for hardware register fields defined in
 * SIDETONE_HDR register yml file. They are automatically extracted by gen_reg.
 *
 */

#ifndef __IAXXX_REGISTER_DEFS_SIDETONE_HDR_H__
#define __IAXXX_REGISTER_DEFS_SIDETONE_HDR_H__

/*** The base address for this set of registers ***/
#define IAXXX_SIDETONE_HDR_REGS_ADDR (0x06000000)

/*** SIDETONE_HDR_ST_CNT (0x06000000) ***/
/*
 * Number of SideTone groups in the SideTone block.
 */
#define IAXXX_SIDETONE_HDR_ST_CNT_ADDR (0x06000000)
#define IAXXX_SIDETONE_HDR_ST_CNT_MASK_VAL 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_CNT_RMASK_VAL 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_CNT_WMASK_VAL 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_CNT_RESET_VAL 0x00000000

/*
 * Number of SideTone groups in the SideTone block.
 */
#define IAXXX_SIDETONE_HDR_ST_CNT_REG_MASK 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_CNT_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_CNT_REG_POS 0
#define IAXXX_SIDETONE_HDR_ST_CNT_REG_SIZE 32

/*** SIDETONE_HDR_ST_EN (0x06000004) ***/
/*
 * Enable/Disable.
 */
#define IAXXX_SIDETONE_HDR_ST_EN_ADDR (0x06000004)
#define IAXXX_SIDETONE_HDR_ST_EN_MASK_VAL 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_EN_RMASK_VAL 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_EN_WMASK_VAL 0xffffffff
#define IAXXX_SIDETONE_HDR_ST_EN_RESET_VAL 0x00000000

/*
 * Enable/Disable SideTone 0
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_0_REG_MASK 0x00000001
#define IAXXX_SIDETONE_HDR_ST_EN_0_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_0_REG_POS 0
#define IAXXX_SIDETONE_HDR_ST_EN_0_REG_SIZE 1

/*
 * Enable/Disable SideTone 1
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_1_REG_MASK 0x00000002
#define IAXXX_SIDETONE_HDR_ST_EN_1_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_1_REG_POS 1
#define IAXXX_SIDETONE_HDR_ST_EN_1_REG_SIZE 1

/*
 * Enable/Disable SideTone 2
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_2_REG_MASK 0x00000004
#define IAXXX_SIDETONE_HDR_ST_EN_2_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_2_REG_POS 2
#define IAXXX_SIDETONE_HDR_ST_EN_2_REG_SIZE 1

/*
 * Enable/Disable SideTone 3
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_3_REG_MASK 0x00000008
#define IAXXX_SIDETONE_HDR_ST_EN_3_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_3_REG_POS 3
#define IAXXX_SIDETONE_HDR_ST_EN_3_REG_SIZE 1

/*
 * Enable/Disable SideTone 4
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_4_REG_MASK 0x00000010
#define IAXXX_SIDETONE_HDR_ST_EN_4_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_4_REG_POS 4
#define IAXXX_SIDETONE_HDR_ST_EN_4_REG_SIZE 1

/*
 * Enable/Disable SideTone 5
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_5_REG_MASK 0x00000020
#define IAXXX_SIDETONE_HDR_ST_EN_5_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_5_REG_POS 5
#define IAXXX_SIDETONE_HDR_ST_EN_5_REG_SIZE 1

/*
 * Enable/Disable SideTone 6
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_6_REG_MASK 0x00000040
#define IAXXX_SIDETONE_HDR_ST_EN_6_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_6_REG_POS 6
#define IAXXX_SIDETONE_HDR_ST_EN_6_REG_SIZE 1

/*
 * Enable/Disable SideTone 7
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_7_REG_MASK 0x00000080
#define IAXXX_SIDETONE_HDR_ST_EN_7_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_7_REG_POS 7
#define IAXXX_SIDETONE_HDR_ST_EN_7_REG_SIZE 1

/*
 * Enable/Disable SideTone 8
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_8_REG_MASK 0x00000100
#define IAXXX_SIDETONE_HDR_ST_EN_8_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_8_REG_POS 8
#define IAXXX_SIDETONE_HDR_ST_EN_8_REG_SIZE 1

/*
 * Enable/Disable SideTone 9
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_9_REG_MASK 0x00000200
#define IAXXX_SIDETONE_HDR_ST_EN_9_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_9_REG_POS 9
#define IAXXX_SIDETONE_HDR_ST_EN_9_REG_SIZE 1

/*
 * Enable/Disable SideTone 10
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_10_REG_MASK 0x00000400
#define IAXXX_SIDETONE_HDR_ST_EN_10_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_10_REG_POS 10
#define IAXXX_SIDETONE_HDR_ST_EN_10_REG_SIZE 1

/*
 * Enable/Disable SideTone 11
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_11_REG_MASK 0x00000800
#define IAXXX_SIDETONE_HDR_ST_EN_11_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_11_REG_POS 11
#define IAXXX_SIDETONE_HDR_ST_EN_11_REG_SIZE 1

/*
 * Enable/Disable SideTone 12
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_12_REG_MASK 0x00001000
#define IAXXX_SIDETONE_HDR_ST_EN_12_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_12_REG_POS 12
#define IAXXX_SIDETONE_HDR_ST_EN_12_REG_SIZE 1

/*
 * Enable/Disable SideTone 13
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_13_REG_MASK 0x00002000
#define IAXXX_SIDETONE_HDR_ST_EN_13_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_13_REG_POS 13
#define IAXXX_SIDETONE_HDR_ST_EN_13_REG_SIZE 1

/*
 * Enable/Disable SideTone 14
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_14_REG_MASK 0x00004000
#define IAXXX_SIDETONE_HDR_ST_EN_14_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_14_REG_POS 14
#define IAXXX_SIDETONE_HDR_ST_EN_14_REG_SIZE 1

/*
 * Enable/Disable SideTone 15
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_15_REG_MASK 0x00008000
#define IAXXX_SIDETONE_HDR_ST_EN_15_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_15_REG_POS 15
#define IAXXX_SIDETONE_HDR_ST_EN_15_REG_SIZE 1

/*
 * Enable/Disable SideTone 16
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_16_REG_MASK 0x00010000
#define IAXXX_SIDETONE_HDR_ST_EN_16_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_16_REG_POS 16
#define IAXXX_SIDETONE_HDR_ST_EN_16_REG_SIZE 1

/*
 * Enable/Disable SideTone 17
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_17_REG_MASK 0x00020000
#define IAXXX_SIDETONE_HDR_ST_EN_17_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_17_REG_POS 17
#define IAXXX_SIDETONE_HDR_ST_EN_17_REG_SIZE 1

/*
 * Enable/Disable SideTone 18
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_18_REG_MASK 0x00040000
#define IAXXX_SIDETONE_HDR_ST_EN_18_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_18_REG_POS 18
#define IAXXX_SIDETONE_HDR_ST_EN_18_REG_SIZE 1

/*
 * Enable/Disable SideTone 19
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_19_REG_MASK 0x00080000
#define IAXXX_SIDETONE_HDR_ST_EN_19_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_19_REG_POS 19
#define IAXXX_SIDETONE_HDR_ST_EN_19_REG_SIZE 1

/*
 * Enable/Disable SideTone 20
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_20_REG_MASK 0x00100000
#define IAXXX_SIDETONE_HDR_ST_EN_20_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_20_REG_POS 20
#define IAXXX_SIDETONE_HDR_ST_EN_20_REG_SIZE 1

/*
 * Enable/Disable SideTone 21
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_21_REG_MASK 0x00200000
#define IAXXX_SIDETONE_HDR_ST_EN_21_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_21_REG_POS 21
#define IAXXX_SIDETONE_HDR_ST_EN_21_REG_SIZE 1

/*
 * Enable/Disable SideTone 22
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_22_REG_MASK 0x00400000
#define IAXXX_SIDETONE_HDR_ST_EN_22_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_22_REG_POS 22
#define IAXXX_SIDETONE_HDR_ST_EN_22_REG_SIZE 1

/*
 * Enable/Disable SideTone 23
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_23_REG_MASK 0x00800000
#define IAXXX_SIDETONE_HDR_ST_EN_23_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_23_REG_POS 23
#define IAXXX_SIDETONE_HDR_ST_EN_23_REG_SIZE 1

/*
 * Enable/Disable SideTone 24
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_24_REG_MASK 0x01000000
#define IAXXX_SIDETONE_HDR_ST_EN_24_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_24_REG_POS 24
#define IAXXX_SIDETONE_HDR_ST_EN_24_REG_SIZE 1

/*
 * Enable/Disable SideTone 25
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_25_REG_MASK 0x02000000
#define IAXXX_SIDETONE_HDR_ST_EN_25_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_25_REG_POS 25
#define IAXXX_SIDETONE_HDR_ST_EN_25_REG_SIZE 1

/*
 * Enable/Disable SideTone 26
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_26_REG_MASK 0x04000000
#define IAXXX_SIDETONE_HDR_ST_EN_26_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_26_REG_POS 26
#define IAXXX_SIDETONE_HDR_ST_EN_26_REG_SIZE 1

/*
 * Enable/Disable SideTone 27
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_27_REG_MASK 0x08000000
#define IAXXX_SIDETONE_HDR_ST_EN_27_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_27_REG_POS 27
#define IAXXX_SIDETONE_HDR_ST_EN_27_REG_SIZE 1

/*
 * Enable/Disable SideTone 28
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_28_REG_MASK 0x10000000
#define IAXXX_SIDETONE_HDR_ST_EN_28_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_28_REG_POS 28
#define IAXXX_SIDETONE_HDR_ST_EN_28_REG_SIZE 1

/*
 * Enable/Disable SideTone 29
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_29_REG_MASK 0x20000000
#define IAXXX_SIDETONE_HDR_ST_EN_29_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_29_REG_POS 29
#define IAXXX_SIDETONE_HDR_ST_EN_29_REG_SIZE 1

/*
 * Enable/Disable SideTone 30
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_30_REG_MASK 0x40000000
#define IAXXX_SIDETONE_HDR_ST_EN_30_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_30_REG_POS 30
#define IAXXX_SIDETONE_HDR_ST_EN_30_REG_SIZE 1

/*
 * Enable/Disable SideTone 31
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SIDETONE_HDR_ST_EN_31_REG_MASK 0x80000000
#define IAXXX_SIDETONE_HDR_ST_EN_31_REG_RESET_VAL 0x0
#define IAXXX_SIDETONE_HDR_ST_EN_31_REG_POS 31
#define IAXXX_SIDETONE_HDR_ST_EN_31_REG_SIZE 1

/* Number of registers in the module */
#define IAXXX_SIDETONE_HDR_REG_NUM 2

#endif /* __IAXXX_REGISTER_DEFS_SIDETONE_HDR_H__ */
