/*
 * iaxxx-register-defs-sensor-header.h
 *
 * Copyright (c) 2018 Knowles, inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

/**********************************************************
 * This file is generated by running a format script
 * on header files shared by Firmware.
 *
 * DO NOT EDIT.
 *
 *********************************************************/

#ifndef __IAXXX_REGISTER_DEFS_SENSOR_HDR_H__
#define __IAXXX_REGISTER_DEFS_SENSOR_HDR_H__

/*** The base address for this set of registers ***/
#define IAXXX_SENSOR_HDR_REGS_ADDR (0x0d000000)

/*** SENSOR_HDR_SENSOR_CNT (0x0d000000) ***/
/*
 * Number of Sensor groups supported in the Sensor block.(Not active sensor
 * count)
 */
#define IAXXX_SENSOR_HDR_SENSOR_CNT_ADDR (0x0d000000)
#define IAXXX_SENSOR_HDR_SENSOR_CNT_MASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_SENSOR_CNT_RMASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_SENSOR_CNT_WMASK_VAL 0x00000000
#define IAXXX_SENSOR_HDR_SENSOR_CNT_RESET_VAL 0x00000000

/*
 * Number of Sensor groups supported in the Sensor block.(Not active sensor
 * count).
 * Sensor manager has this many number of endpoints and are one-to-one
 * mapped.
 */
#define IAXXX_SENSOR_HDR_SENSOR_CNT_REG_MASK 0xffffffff
#define IAXXX_SENSOR_HDR_SENSOR_CNT_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_CNT_REG_POS 0
#define IAXXX_SENSOR_HDR_SENSOR_CNT_REG_SIZE 32

/*** SENSOR_HDR_SENSOR_ENABLE (0x0d000004) ***/
/*
 * Enable/Disable Sensors.
 */
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_ADDR (0x0d000004)
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_MASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_RMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_WMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_RESET_VAL 0x00000000

/*
 * Enable/Disable Sensor 0
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_0_REG_MASK 0x00000001
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_0_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_0_REG_POS 0
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_0_REG_SIZE 1

/*
 * Enable/Disable Sensor 1
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_1_REG_MASK 0x00000002
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_1_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_1_REG_POS 1
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_1_REG_SIZE 1

/*
 * Enable/Disable Sensor 2
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_2_REG_MASK 0x00000004
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_2_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_2_REG_POS 2
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_2_REG_SIZE 1

/*
 * Enable/Disable Sensor 3
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_3_REG_MASK 0x00000008
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_3_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_3_REG_POS 3
#define IAXXX_SENSOR_HDR_SENSOR_ENABLE_3_REG_SIZE 1

/*** SENSOR_HDR_SENSOR_STATE (0x0d000008) ***/
/*
 * Enabled/Disabled State of Sensors.
 */
#define IAXXX_SENSOR_HDR_SENSOR_STATE_ADDR (0x0d000008)
#define IAXXX_SENSOR_HDR_SENSOR_STATE_MASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SENSOR_STATE_RMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SENSOR_STATE_WMASK_VAL 0x00000000
#define IAXXX_SENSOR_HDR_SENSOR_STATE_RESET_VAL 0x00000000

/*
 * State of Sensor 0
 * 0 - Disabled
 * 1 - Enabled
 */
#define IAXXX_SENSOR_HDR_SENSOR_STATE_0_REG_MASK 0x00000001
#define IAXXX_SENSOR_HDR_SENSOR_STATE_0_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_STATE_0_REG_POS 0
#define IAXXX_SENSOR_HDR_SENSOR_STATE_0_REG_SIZE 1

/*
 * State of Sensor 1
 * 0 - Disabled
 * 1 - Enabled
 */
#define IAXXX_SENSOR_HDR_SENSOR_STATE_1_REG_MASK 0x00000002
#define IAXXX_SENSOR_HDR_SENSOR_STATE_1_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_STATE_1_REG_POS 1
#define IAXXX_SENSOR_HDR_SENSOR_STATE_1_REG_SIZE 1

/*
 * State of Sensor 2
 * 0 - Disabled
 * 1 - Enabled
 */
#define IAXXX_SENSOR_HDR_SENSOR_STATE_2_REG_MASK 0x00000004
#define IAXXX_SENSOR_HDR_SENSOR_STATE_2_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_STATE_2_REG_POS 2
#define IAXXX_SENSOR_HDR_SENSOR_STATE_2_REG_SIZE 1

/*
 * State of Sensor 3
 * 0 - Disabled
 * 1 - Enabled
 */
#define IAXXX_SENSOR_HDR_SENSOR_STATE_3_REG_MASK 0x00000008
#define IAXXX_SENSOR_HDR_SENSOR_STATE_3_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SENSOR_STATE_3_REG_POS 3
#define IAXXX_SENSOR_HDR_SENSOR_STATE_3_REG_SIZE 1

/*** SENSOR_HDR_SET_PARAM_REQ (0x0d00000c) ***/
/*
 * This register is used to request SetParam to
 * any Sensor Instance(s). This register write is
 * accompanied by writing to appropriate ParamId
 * and ParamVal registers from Sensor Instance Group.
 */
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_ADDR (0x0d00000c)
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_MASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_RMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_WMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_RESET_VAL 0x00000000

/*
 * Request Set Param to sensor instance 0
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_0_MASK 0x00000001
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_0_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_0_POS 0
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_0_SIZE 1

/*
 * Request Set Param to sensor instance 1 The bit is cleared on completion of
 * task.
 */
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_1_MASK 0x00000002
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_1_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_1_POS 1
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_1_SIZE 1

/*
 * Request Set Param to sensor instance 2
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_2_MASK 0x00000004
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_2_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_2_POS 2
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_2_SIZE 1

/*
 * Request Set Param to sensor instance 3
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_3_MASK 0x00000008
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_3_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_3_POS 3
#define IAXXX_SENSOR_HDR_SET_PARAM_REQ_SENSOR_3_SIZE 1

/*** SENSOR_HDR_GET_PARAM_REQ (0x0d000010) ***/
/*
 * This register is used to request GetParam to
 * any Sensor Instance(s). This register write is
 * accompanied by writing to appropriate ParamId
 * registers from Sensor Instance Group.
 */
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_ADDR (0x0d000010)
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_MASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_RMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_WMASK_VAL 0x0000000f
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_RESET_VAL 0x00000000

/*
 * Request Get Param from sensor instance 0
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_0_MASK 0x00000001
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_0_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_0_POS 0
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_0_SIZE 1

/*
 * Request Get Param from sensor instance 1
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_1_MASK 0x00000002
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_1_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_1_POS 1
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_1_SIZE 1

/*
 * Request Get Param from sensor instance 2
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_2_MASK 0x00000004
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_2_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_2_POS 2
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_2_SIZE 1

/*
 * Request Get Param from sensor instance 3
 * The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_3_MASK 0x00000008
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_3_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_3_POS 3
#define IAXXX_SENSOR_HDR_GET_PARAM_REQ_SENSOR_3_SIZE 1

/*** SENSOR_HDR_PARAM_BLK_CTRL (0x0d000014) ***/
/*
 * This register is used as a control register to
 * Set Param Block to a particular sensor instance.
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_ADDR (0x0d000014)
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_MASK_VAL 0x03ffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_RMASK_VAL 0x03ffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_WMASK_VAL 0x03ffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_RESET_VAL 0x00000000

/*
 * Block size
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_BLK_SIZE_MASK 0x000fffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_BLK_SIZE_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_BLK_SIZE_POS 0
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_BLK_SIZE_SIZE 20

/*
 * Sensor Instance Id for Param Block operation
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_INSTANCE_ID_MASK 0x00f00000
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_INSTANCE_ID_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_INSTANCE_ID_POS 20
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_INSTANCE_ID_SIZE 4

/*
 * Indicate that the Param Block has been written to the memory The bit is
 * cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_DONE_MASK 0x01000000
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_DONE_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_DONE_POS 24
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_DONE_SIZE 1

/*
 * Request SetParamBlock The bit is cleared on completion of task.
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_REQ_MASK 0x02000000
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_REQ_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_REQ_POS 25
#define IAXXX_SENSOR_HDR_PARAM_BLK_CTRL_SET_BLK_REQ_SIZE 1

/*** SENSOR_HDR_PARAM_BLK_ID (0x0d000018) ***/
/*
 * Param Id for Set Param block.
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_ADDR (0x0d000018)
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_MASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_RMASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_WMASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_RESET_VAL 0x00000000

/*
 * 4-byte Opaque Header
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_REG_MASK 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_REG_POS 0
#define IAXXX_SENSOR_HDR_PARAM_BLK_ID_REG_SIZE 32

/*** SENSOR_HDR_PARAM_BLK_ADDR (0x0d00001c) ***/
/*
 * Address of the Param Block.
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_ADDR (0x0d00001c)
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_MASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_WMASK_VAL 0x00000000
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_RESET_VAL 0x00000000

/*
 * Address to Set Param block.
 */
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_REG_MASK 0xffffffff
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_REG_RESET_VAL 0x0
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_REG_POS 0
#define IAXXX_SENSOR_HDR_PARAM_BLK_ADDR_REG_SIZE 32

/* Number of registers in the module */
#define IAXXX_SENSOR_HDR_REG_NUM 8

#endif /* __IAXXX_REGISTER_DEFS_SENSOR_HDR_H__ */
