/*
 * ia8508a-memory-map.h -- IA8508A memory map header file
 *
 * Copyright 2019 Knowles Corporation
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 */

#ifndef __IA8508A_MEMORY_MAP_H__
#define __IA8508A_MEMORY_MAP_H__

#include <linux/kernel.h>
#include "iaxxx.h"
/******************* ROM START ADDR *********************/
#define IAXXX_HMD_DROM_SYS_START	0xA6200000
#define IAXXX_HMD_IROM_SYS_START	0xA6600000
#define IAXXX_DMX_DROM_SYS_START	0xA8200000
#define IAXXX_DMX_IROM_SYS_START	0xA8600000

#define IAXXX_CM4_MAC_IRAM0_WIN0_OFFSET_ADDR	0x50032008
#define IAXXX_CM4_MAC_DRAM0_WIN0_OFFSET_ADDR	0x50032028
#define IAXXX_DMX_MAC_IRAM0_WIN0_OFFSET_ADDR	0x50034008
#define IAXXX_DMX_MAC_DRAM0_WIN0_OFFSET_ADDR	0x50034028
#define IAXXX_HMD_MAC_IRAM0_WIN0_OFFSET_ADDR	0x50033008
#define IAXXX_HMD_MAC_DRAM0_WIN0_OFFSET_ADDR	0x50033028

#define IAXXX_CM4_MAC_IRAM0_WIN1_OFFSET_ADDR (0x50032010)
#define IAXXX_CM4_MAC_DRAM0_WIN1_OFFSET_ADDR (0x50032030)
#define IAXXX_HMD_MAC_IRAM0_WIN1_OFFSET_ADDR (0x50033010)
#define IAXXX_HMD_MAC_DRAM0_WIN1_OFFSET_ADDR (0x50033030)
#define IAXXX_DMX_MAC_IRAM0_WIN1_OFFSET_ADDR (0x50034010)
#define IAXXX_DMX_MAC_DRAM0_WIN1_OFFSET_ADDR (0x50034030)

#define IAXXX_CM4_IMEM_LCL_START	0x00000000
#define IAXXX_CM4_IMEM_LCL_END		0x00400000
#define IAXXX_CM4_DMEM_LCL_START	0x20000000
#define IAXXX_CM4_DMEM_LCL_END		0x20400000
#define IAXXX_HMD_IMEM_SYS_START	0xA6400000
#define IAXXX_HMD_IMEM_SYS_END		0xA6800000
#define IAXXX_HMD_DMEM_SYS_START	0xA6000000
#define IAXXX_HMD_DMEM_SYS_END		0xA6400000
#define IAXXX_DMX_IMEM_SYS_START	0xA8400000
#define IAXXX_DMX_IMEM_SYS_END		0xA8800000
#define IAXXX_DMX_DMEM_SYS_START	0xA8000000
#define IAXXX_DMX_DMEM_SYS_END		0xA8400000
#define IAXXX_SSP_DRAM0_SYS_START	0xA2000000
#define IAXXX_SSP_DRAM0_SYS_END		0xA2008000
#define IAXXX_SSP_DRAM1_SYS_START	0xA3000000
#define IAXXX_SSP_DRAM1_SYS_END		0xA3008000
#define IAXXX_SSP_DROM0_SYS_START	0xA2200000
#define IAXXX_SSP_DROM0_SYS_END		0xA2202000

#define IAXXX_MAC_WINDOW_SIZE		1024

enum mem_type_t {
	MEM_TYPE_TEXT,
	MEM_TYPE_DATA
};

#define IAXXX_ROM_ADDR_MAPPING { \
	IAXXX_HMD_DROM_SYS_START, \
	IAXXX_HMD_IROM_SYS_START, \
	IAXXX_DMX_DROM_SYS_START, \
	IAXXX_DMX_IROM_SYS_START, \
}

/* MAC register address */
#define IAXXX_MAC_REG_ADDR_MAPPING		\
{						\
	{IAXXX_CM4_MAC_IRAM0_WIN0_OFFSET_ADDR,	\
		IAXXX_CM4_MAC_IRAM0_WIN1_OFFSET_ADDR},	\
	{IAXXX_CM4_MAC_DRAM0_WIN0_OFFSET_ADDR,	\
		IAXXX_CM4_MAC_DRAM0_WIN1_OFFSET_ADDR},	\
	{IAXXX_HMD_MAC_IRAM0_WIN0_OFFSET_ADDR,	\
		IAXXX_HMD_MAC_IRAM0_WIN1_OFFSET_ADDR},	\
	{IAXXX_HMD_MAC_DRAM0_WIN0_OFFSET_ADDR,	\
		IAXXX_HMD_MAC_DRAM0_WIN1_OFFSET_ADDR},	\
	{IAXXX_DMX_MAC_IRAM0_WIN0_OFFSET_ADDR,	\
		IAXXX_DMX_MAC_IRAM0_WIN1_OFFSET_ADDR},	\
	{IAXXX_DMX_MAC_DRAM0_WIN0_OFFSET_ADDR,	\
		IAXXX_DMX_MAC_DRAM0_WIN1_OFFSET_ADDR},	\
}

#define IAXXX_PROC_ID_TYPE_MAPPING			\
{							\
	{IAXXX_CM4_IMEM_LCL_START, IAXXX_CM4_IMEM_LCL_END, IAXXX_CM4_ID, \
		MEM_TYPE_TEXT},\
	{IAXXX_CM4_DMEM_LCL_START, IAXXX_CM4_DMEM_LCL_END, IAXXX_CM4_ID, \
		MEM_TYPE_DATA},\
	{IAXXX_HMD_IMEM_SYS_START, IAXXX_HMD_IMEM_SYS_END, IAXXX_HMD_ID, \
		MEM_TYPE_TEXT},\
	{IAXXX_HMD_DMEM_SYS_START, IAXXX_HMD_DMEM_SYS_END, IAXXX_HMD_ID, \
		MEM_TYPE_DATA},\
	{IAXXX_DMX_IMEM_SYS_START, IAXXX_DMX_IMEM_SYS_END, IAXXX_DMX_ID, \
		MEM_TYPE_TEXT},\
	{IAXXX_DMX_DMEM_SYS_START, IAXXX_DMX_DMEM_SYS_END, IAXXX_DMX_ID, \
		MEM_TYPE_DATA},\
}

#define MAX_ADDR_ROM_SIZE	(64 * 1024)

#define IS_WITHIN_ROM_ADDRESS_RANGE(addr, start, size) \
	(((addr) >= (start)) && ((addr) < ((start) + (size))))

#define IS_PHY_START_ADDR_IN_ROM_ADDRESS_RANGE(addr, start) \
	(((addr) <= (start)) && ((addr + MAX_ADDR_ROM_SIZE) > start))
/******************* ROM START ADDR END *******************/

void rom_phy_address_range_check_and_update(uint32_t *phy_addr,
		uint32_t in_bytes, uint32_t *phy_size1,
		uint32_t *phy_addr2, uint32_t *phy_size2);

#endif /* __IA8508A_MEMORY_MAP_H__ */
