#
# Makefile for Audience MFD & related Modules
#
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-core.o iaxxx-boot.o iaxxx-srb.o iaxxx-plugin.o iaxxx-event.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-regmap.o iaxxx-evnt-mgr.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-dbgfs.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-tunnel.o iaxxx-tunnel-dev.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-debug.o iaxxx-cdev.o
obj-$(CONFIG_MFD_IAXXX_I2C)	+= iaxxx-i2c.o
obj-$(CONFIG_MFD_IAXXX_SPI)	+= iaxxx-spi.o
obj-$(CONFIG_MFD_IAXXX_SOUNDWIRE)	+= iaxxx-swr.o
