#
# Makefile for Audience MFD & related Modules
#
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-core.o iaxxx-boot.o iaxxx-srb.o iaxxx-plugin.o iaxxx-event.o iaxxx-module.o iaxxx-plugin-common.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-regmap.o iaxxx-evnt-mgr.o iaxxx-pwr-mgmt.o ia8508a-memory-map.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-dbgfs.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-tunnel.o iaxxx-tunnel-dev.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-debug.o iaxxx-cdev.o iaxxx-debug-logging.o iaxxx-sysfs.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-btp.o iaxxx-static-mem.o
obj-$(CONFIG_MFD_IAXXX_SENSOR_TUNNEL)		+= iaxxx-sensor-tunnel.o
obj-$(CONFIG_MFD_IAXXX_I2C)	+= iaxxx-i2c.o
obj-$(CONFIG_MFD_IAXXX_SPI)	+= iaxxx-spi.o
obj-$(CONFIG_MFD_IAXXX_SOUNDWIRE)	+= iaxxx-swr.o
obj-$(CONFIG_MFD_IAXXX_CUSTOM_CONFIG_ALGO)	+= iaxxx-plg-custom-cfg.o
obj-$(CONFIG_MFD_IAXXX)		+= iaxxx-misc.o
