obj-$(CONFIG_GOOGLE_CHARGER)	+= google_charger.o
obj-$(CONFIG_GOOGLE_BATTERY)	+= google-battery.o
google-battery-objs += google_battery.o google_ttf.o
obj-$(CONFIG_GOOGLE_BMS)	+= google_bms.o
obj-$(CONFIG_GOOGLE_BMS)    	+= sm7250_bms.o
obj-$(CONFIG_USB_OVERHEAT_MITIGATION)	+= overheat_mitigation.o
obj-$(CONFIG_GOOGLE_LOGBUFFER)		+= logbuffer.o
