obj-$(CONFIG_GOOGLE_BMS)	+= gbms_storage.o gvotable.o  google_bms.o
obj-$(CONFIG_GOOGLE_CHARGER)	+= google_charger.o
obj-$(CONFIG_GOOGLE_BATTERY)	+= google_battery.o google_ttf.o
obj-$(CONFIG_USB_OVERHEAT_MITIGATION)	+= overheat_mitigation.o
obj-$(CONFIG_ARCH_SM8150)    	+= sm8150_bms.o
obj-$(CONFIG_ARCH_SM6150)       += sm7150_bms.o
obj-$(CONFIG_GOOGLE_LOGBUFFER)	+= logbuffer.o
obj-$(CONFIG_CHARGER_P9221)	+= p9221_charger.o
