ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += icp_hw_mgr/ a5_hw/ ipe_hw/ bps_hw/
