#
# Makefile for the focaltech FT3267 touchscreen drivers.
#


obj-$(CONFIG_TOUCHSCREEN_FT3267) += fts_ts.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_core.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_ctl.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_ex_fun.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_flash.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += test_lib.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += ini.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += Global.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += Config_FT6X36.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += Test_FT6X36.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += DetailThreshold.o
fts_ts-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_gesture.o
