#
# Makefile for the focaltech FT3267 touchscreen drivers.
#


obj-$(CONFIG_TOUCHSCREEN_FT3267) += ft_3267.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_core.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_ctl.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_ex_fun.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_flash.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += test_lib.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += ini.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += Global.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += Config_FT6X36.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += Test_FT6X36.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += DetailThreshold.o
ft_3267-$(CONFIG_TOUCHSCREEN_FT3267) += focaltech_gesture.o
