# SPDX-License-Identifier: GPL-2.0
#
# Makefile for kernel SLIMbus framework.
#
obj-$(CONFIG_SLIMBUS)			+= slimbus.o
obj-$(CONFIG_SLIMBUS_MSM_CTRL)		+= slim_msm_ctrl.o
slim_msm_ctrl-objs += slim-msm.o slim-msm-ctrl.o
obj-$(CONFIG_SLIMBUS_MSM_NGD)		+= slim_msm_ngd.o
slim_msm_ngd-objs += slim-msm.o slim-msm-ngd.o
