#
# Makefile for paintbox programmable IPU.
#
obj-$(CONFIG_IPU_AB_MFD_ADAPTER)	+= ipu-adapter-ab-mfd.o
obj-$(CONFIG_IPU)			+= ipu-buffer.o
obj-$(CONFIG_IPU)			+= ipu-client.o
obj-$(CONFIG_IPU)			+= ipu-core.o
obj-$(CONFIG_IPU)			+= ipu-core-jqs.o
obj-$(CONFIG_IPU)			+= ipu-core-jqs-cbuf.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-core-jqs-debug.o
obj-$(CONFIG_IPU)			+= ipu-core-jqs-msg-transport.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-aon-debug.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-apb-debug.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-bif-debug.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-debug.o
obj-$(CONFIG_IPU)			+= ipu-dma.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-dma-debug.o
obj-$(CONFIG_IPU)			+= ipu-lbp.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-lbp-debug.o
obj-$(CONFIG_IPU_DEBUG) 		+= ipu-mmu.o
obj-$(CONFIG_IPU)			+= ipu-power.o
obj-$(CONFIG_IPU)			+= ipu-queue.o
obj-$(CONFIG_IPU)			+= ipu-resource.o
obj-$(CONFIG_IPU)			+= ipu-stp.o
obj-$(CONFIG_IPU_DEBUG)			+= ipu-stp-debug.o
