dtb-$(CONFIG_BOARD_MUSKIE) += \
	msm8998-v2.1-htc_muskie-xb.dtb \
	msm8998-v2.1-htc_muskie-xa.dtb \
	msm8998-v2.1-htc_muskie-evm.dtb \
	msm8998-htc_muskie-evm.dtb \

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
