dtb-$(CONFIG_ARCH_MSM8996) += \
	msm8996pro-v1.1-htc_marlin-a.dtb \
	msm8996pro-v1.1-htc_sailfish-a.dtb \
	msm8996pro-htc_marlin-a.dtb \
	msm8996pro-htc_sailfish-a.dtb \
	msm8996pro-v1.1-htc_marlin-xd.dtb \
	msm8996pro-v1.1-htc_sailfish-xd.dtb \
	msm8996pro-htc_marlin-xd.dtb \
	msm8996pro-htc_sailfish-xd.dtb \
	msm8996pro-v1.1-htc_marlin-xc.dtb \
	msm8996pro-v1.1-htc_sailfish-xc.dtb \
	msm8996pro-htc_marlin-xc.dtb \
	msm8996pro-htc_sailfish-xc.dtb \
	msm8996pro-htc_marlin-xb.dtb \
	msm8996pro-htc_sailfish-xb.dtb \
	msm8996-v3-htc_marlin-xb.dtb \
	msm8996-v3-htc_sailfish-xb.dtb \
	msm8996pro-htc_marlin-xa.dtb \
	msm8996pro-htc_sailfish-xa.dtb \
	msm8996-v3-htc_marlin-xa.dtb \
	msm8996-v3-htc_sailfish-xa.dtb \

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files := *.dtb
