dtb-$(CONFIG_ARCH_MSM8996) += \
	msm8996-v3-htc_t50-xc.dtb \
	msm8996-v3-htc_t50-xb.dtb \
	msm8996-v3-htc_t50-xa.dtb \

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files := *.dtb
