#ifndef __FACEAUTH_SHARED_H__
#define __FACEAUTH_SHARED_H__
/*  The error codes are broken up into functional groups with space reserve for
 *  future error codes. The divisions are as follows:
 *  0     - success
 *  1     - general error (debug only, never used)
 *  2-31  - TPU device driver errors (inherrited from the TPU driver)
 *  32-47 - Errors returned from the citadel chip
 *  48-63 - Errors returned form the M0 citadel code
 *  64+   - TPU/IPU model errors and M0 processing errors
 */
#define ERROR_NO_ERROR 0
#define ERROR_GENERAL_ERROR -1
// -2 to -31 are reserved for tpu errors, defined in tpu_error.h
// errors returned from the citadel chip
#define ERROR_INTERNAL_CITADEL_INVALID_ARGS -32
#define ERROR_INTERNAL_CITADEL_TIMEOUT -33
#define ERROR_INTERNAL_CITADEL_ERR_THROTTLE -34
#define ERROR_INTERNAL_CITADEL_SFS_INTERNAL -35
#define ERROR_INTERNAL_CITADEL_SFS_FULL -36
#define ERROR_INTERNAL_CITADEL_SESSION_ID -37
#define ERROR_INTERNAL_CITADEL_CRC -38
#define ERROR_INTERNAL_CITADEL_ERR_UNKNOWN -39

// errors generated by the M0 citadel code
#define ERROR_CITADEL_TIMEOUT -48
#define ERROR_CITADEL_SESSION_ID -49
#define ERROR_CITADEL_CRC -50
#define ERROR_CITADEL_EARLY_FAIL -51
#define ERROR_CITADEL_UNSUPPORTED -52

// models errors
#define ERROR_DEPTH_IPU_TIMEOUT -64
#define ERROR_SKIN_INVALID_LAYER_SIZE -65
#define ERROR_SKIN_INVALID_FACE_BUFFER -66
#define ERROR_SKIN_INVALID_PATCH_SIZE -67
#define ERROR_SKIN_INVALID_FACE_SIZE -68
#define ERROR_DOWNSCALE_IPU_TIMEOUT -69
#define ERROR_AFFINE_COMBINED_IPU_TIMEOUT -70


/* Any change to the WorkloadStatus should also be accompanied by a change to
 * WORKLOAD_STATUS_STRINGS below.
 */
typedef enum _workload_status {
	WORKLOAD_STATUS_NO_STATUS = 0,
	WORKLOAD_STATUS_PASS,
	//Reject (post)FSSD code when no face is found
	WORKLOAD_STATUS_FSSD_REJECT_NO_FACE,
	//Reject (post)FSSD code when multiple faces are found
	WORKLOAD_STATUS_FSSD_REJECT_MULTIPLE_FACE,
	//Reject (post)FDDS code when number of faces is more than capacity
	WORKLOAD_STATUS_FSSD_REJECT_MAX_FACE_CAPACITY,
	//Reject Gazenet for no camera attention, optionally can be ignored
	WORKLOAD_STATUS_GAZE_REJECT_NO_ATTENTION,
	//Reject Skin (Mask?)
	WORKLOAD_STATUS_SKIN_REJECT,
	//Reject Depth Remap when unable to find 5 percentile
	WORKLOAD_STATUS_DEPTH_REMAP_REJECT,
	//Rejection from Citadel
	WORKLOAD_STATUS_CITADEL_REJECT,
	WORKLOAD_STATUS_ERROR = 0xffff,

	WORKLOAD_STATUS_COUNT,
	WORKLOAD_STATUS_INTMAX = 0xffffffff
} WorkloadStatus;


#endif /* __FACEAUTH_SHARED_H__ */
