#gt1x touchpanel driver


obj-$(CONFIG_GT1X_TOUCHPANEL_DRIVER)	+= gt1x.o
obj-$(CONFIG_GT1X_TOUCHPANEL_DRIVER)	+= gt1x_extents.o
obj-$(CONFIG_GT1X_TOUCHPANEL_DRIVER)	+= gt1x_generic.o
#gt1x update file
obj-$(CONFIG_GT1X_TOUCHPANEL_UPDATE)	+= gt1x_update.o
#debug tool
obj-$(CONFIG_GT1X_TOUCHPANEL_DEBUG)	+= gt1x_tools.o