/*
* Copyright c 2016 PixArt Imaging Inc.. All Rights Reserved.

* This program is free software; you may redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2 of the License.

* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
* BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
* ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
* CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/
#ifndef _PIXART_OTS_H_
#define _PIXART_OTS_H_

#include  "pixart_platform.h"

/*export funtions*/
void OTS_Reset_Variables(void);
unsigned char OTS_Detect_Rotation(int16_t dx16, int16_t dy16);
unsigned char OTS_Check_MotionAndButton(int16_t *dx16, int16_t *dy16);
bool OTS_Sensor_Init(int check_calib, uint8_t s_c, uint8_t s_f, uint8_t btn_hi,
	uint8_t btn_lo, int16_t res_x);
void OTS_Sensor_ReadMotion(int16_t *dx, int16_t *dy) ;
void OTS_WriteRead_Reg(uint8_t address, uint8_t wdata);

/* Register addresses */
#define PIXART_PAT9127_PRODUCT_ID1_REG			0x00
#define PIXART_PAT9127_MOTION_STATUS_REG		0x02
#define PIXART_PAT9127_DELTA_X_LO_REG			0x03
#define PIXART_PAT9127_DELTA_Y_LO_REG			0x04
#define PIXART_PAT9127_CONFIG_REG			0x06
#define PIXART_PAT9127_SET_CPI_RES_X_REG		0x0D
#define PIXART_PAT9127_SET_CPI_RES_Y_REG		0x0E
#define PIXART_PAT9127_DELTA_XY_HI_REG			0x12
#define PIXART_PAT9127_FRAME_AVG_REG			0x17
#define PIXART_PAT9127_SHUTTER_C_REG			0x2D
#define PIXART_PAT9127_SHUTTER_F_REG			0x2F
#define PIXART_PAT9127_BTN_HITHD_REG			0x3E
#define PIXART_PAT9127_BTN_LOTHD_REG			0x3F
#define PIXART_PAT9127_VOLTAGE_SEGMENT_SEL_REG		0x4B
#define PIXART_PAT9127_SENSOR_MODE_SELECT_REG		0x7C
#define PIXART_PAT9127_SELECT_BANK_REG			0x7F
/*Register configuration data */
#define PIXART_PAT9127_SENSOR_ID			0x31
#define PIXART_PAT9127_RESET				0x97
#define PIXART_PAT9127_BANK0				0x00
#define PIXART_PAT9127_FRAME_AVG_RLS_MAX		0x91
#define PIXART_PAT9127_FRAME_AVG_RLS_MIN		0x87
#define PIXART_PAT9127_ROTATED_FRAME_AVG_RLS_MAX	0x96
#define PIXART_PAT9127_ROTATED_FRAME_AVG_RLS_MIN	0x82
#define PIXART_PAT9127_FA_SHUTTER_C_MAX			0x0F
#define PIXART_PAT9127_FA_SHUTTER_C_MIN			0x00
#define PIXART_PAT9127_FA_SHUTTER_F_MAX			0x15
#define PIXART_PAT9127_FA_SHUTTER_F_MIN			0x05
#define PIXART_PAT9127_MOTION_COUNT_MAX			0x6E
#define PIXART_PAT9127_MOTION_COUNT_DEFAULT		0x64
#define PIXART_PAT9127_MOTION_COUNT_MIN			0x5A
#define PIXART_PAT9127_VALID_PRESS_BIT_DATA		0x01
#define PIXART_PAT9127_VALID_RELEASE_DATA		0x02
#define PIXART_PAT9127_VALID_PRE_AND_REL_DATA		0x03
#define PIXART_PAT9127_VALID_MOTION_DATA		0x80
#define PIXART_PAT9127_CHK_MOT_AND_BTN_DATA		0x83
#define PIXART_PAT9127_CPI_RES_X_DEFAULT		0x80
#define PIXART_PAT9127_CPI_RES_Y_DEFAULT		0x00
#define PIXART_PAT9127_SENSOR_SET_MODE			0xCC
#define PIXART_PAT9127_SENSOR_DEFAULT_MODE		0xC8
#define PIXART_PAT9127_CPI_RESOLUTION_X			0x44
#define PIXART_PAT9127_CPI_RESOLUTION_Y			0x00
#define PIXART_PAT9127_LOW_VOLTAGE_SEGMENT		0x04
#define PIXART_PAT9127_CPI_STEP				3
#define PIXART_PAT9127_SHUTTER_C_DEFAULT		0x0E
#define PIXART_PAT9127_SHUTTER_F_DEFAULT		0x05
#define PIXART_PAT9127_BTN_HITHD_DEFAULT		0x78
#define PIXART_PAT9127_BTN_LOTHD_DEFAULT		0x46

/*define OTS state - X*/
#define OTS_ROT_NO_CHANGE	0x00
#define OTS_ROT_UP		0x01
#define OTS_ROT_DOWN		0x02

/*define OTS state*/
#define OTS_BTN_NO_CHANGE	0x00
#define OTS_BTN_PRESS		0x01
#define OTS_BTN_RELEASE		0x02
#define OTS_BTN_PRE_AND_REL	0x03

#endif
