ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_jpeg
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_jpeg/jpeg_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_jpeg/jpeg_hw/
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_jpeg/jpeg_hw/jpeg_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_floral/cam_jpeg/jpeg_hw/jpeg_enc_hw

obj-$(CONFIG_SPECTRA_CAMERA) += jpeg_enc_dev.o jpeg_enc_core.o jpeg_enc_soc.o
