#
# Makefile for the vd6281 drivers.
#

ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_req_mgr
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_smmu/
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_sync
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_cci
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_utils
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_cpas/include
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_io
ccflags-$(CONFIG_INPUT_VD6281) += -Idrivers/media/platform/msm/camera/cam_core

obj-$(CONFIG_INPUT_VD6281) += vd6281_module.o
