#
# Makefile for paintbox programmable IPU.
#

obj-$(CONFIG_PAINTBOX)				+= paintbox.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-bif.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-bus.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-bus-jqs.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-debug.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma-common.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma-debug.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma-dram.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma-lbp.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma-stp.o
obj-$(CONFIG_PAINTBOX_FPGA_SUPPORT)		+= paintbox-fpga.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-io.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-irq.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-lbp.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-lbp-debug.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-mmu.o
obj-$(CONFIG_PAINTBOX_PLATFORM_BUS)		+= paintbox-platform.o
obj-$(CONFIG_PAINTBOX_AIRBRUSH_MFD)		+= paintbox-airbrush-mfd.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-pmon.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-power.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-sram.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-stp.o
obj-$(CONFIG_PAINTBOX_DEBUG)			+= paintbox-stp-debug.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-stp-pc-histogram.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-stp-sram.o
