#
#  Makefile for Gasket framework and dependent drivers.
#

obj-$(CONFIG_GASKET_FRAMEWORK)	+= gasket.o
obj-$(CONFIG_OSCAR_DRIVER)	+= oscar.o

gasket-objs	:= gasket_core.o gasket_ioctl.o gasket_interrupt.o gasket_page_table.o gasket_sysfs.o
oscar-objs	:= oscar_platform_driver.o
