dtbo-$(CONFIG_BOARD_TAIMEN) += \
	overlay-taimen-rev-0.dtbo \
	overlay-taimen-rev-a.dtbo \
	overlay-taimen-rev-b.dtbo \
	overlay-taimen-rev-c.dtbo \
	overlay-taimen-rev-d.dtbo \
	overlay-taimen-rev-e.dtbo \
	overlay-taimen-rev-1_0.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
