/*
 * Copyright (c) 2018 Samsung Electronics Co., Ltd.
 * Author: Raman Kumar Banka <raman.k2@samsung.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */

#include <linux/clk-provider.h>
#include <linux/of.h>
#include "clk.h"
#include <dt-bindings/clock/abc-clk.h>

#define CONFIG_A0

/*********************CMU_AON****************************/
/* Register Offset definitions for CMU_AON (0x10B10000) */
#define PLL_LOCKTIME_PLL_AON	0x0
#define PLL_CON0_PLL_AON	0x100
#define PLL_CON1_PLL_AON	0x104
#define PLL_CON2_PLL_AON	0x108
#define PLL_CON4_PLL_AON	0x110
#define AON_CMU_AON_CONTROLLER_OPTION	0x800
#define CLKOUT_CON_BLK_AON_CMU_AON_CLKOUT0	0x810
#define CLKOUT_CON_BLK_AON_CMU_AON_CLKOUT1	0x814
#define CLK_CON_DIV_DIV4_PLLCLK	0x1800
#define CLK_CON_DIV_DIV_OTP	0x1804
#define CLK_CON_DIV_DIV_TMU	0x1808
#define CLK_CON_DIV_PLL_AON_CLK	0x180c
#define CLK_CON_DIV_SHARED_DIV_AON_PLL	0x1810
#define CLK_CON_DIV_SHARED_DIV_MIF	0x1814
#define CLK_CON_GAT_CLK_BLK_AON_UID_ABC_INTMEM_IPCLKPORT_ACLK	0x2000
#define CLK_CON_GAT_CLK_BLK_AON_UID_AON_CMU_AON_IPCLKPORT_PCLK	0x2004
#define CLK_CON_GAT_CLK_BLK_AON_UID_AON_SPI0_IPCLKPORT_I_AON_CLK	0x2008
#define CLK_CON_GAT_CLK_BLK_AON_UID_AON_UART_IPCLKPORT_I_PCLK	0x200c
#define CLK_CON_GAT_CLK_BLK_AON_UID_AON_UART_IPCLKPORT_I_SCLK_UART	0x2010
#define CLK_CON_GAT_CLK_BLK_AON_UID_AXI2APB_AON_IPCLKPORT_ACLK	0x2014
#define CLK_CON_GAT_CLK_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_CLK	0x2018
#define CLK_CON_GAT_CLK_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_CLK	0x201c
#define CLK_CON_GAT_CLK_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_CLK	0x2020
#define CLK_CON_GAT_CLK_BLK_AON_UID_CENTRAL_PMU_IPCLKPORT_PCLK	0x2024
#define CLK_CON_GAT_CLK_BLK_AON_UID_GPIO_ASYNCBR_TOP_AON_IPCLKPORT_PCLK	0x2028
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_DCLK	0x202c
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_FCLK	0x2030
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_HCLK	0x2034
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_SCLK	0x2038
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_RAM_IPCLKPORT_CLK	0x203c
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_RAM_IPCLKPORT_HCLK	0x2040
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_ROM_IPCLKPORT_CLK	0x2044
#define CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_ROM_IPCLKPORT_HCLK	0x2048
#define CLK_CON_GAT_CLK_BLK_AON_UID_NIC_AON_IPCLKPORT_MAINCLK	0x204c
#define CLK_CON_GAT_CLK_BLK_AON_UID_OTP_AON_IPCLKPORT_OSCCLK	0x2050
#define CLK_CON_GAT_CLK_BLK_AON_UID_OTP_AON_IPCLKPORT_PCLK	0x2054
#define CLK_CON_GAT_CLK_BLK_AON_UID_SYSREG_AON_IPCLKPORT_CLK	0x2058
#define CLK_CON_GAT_CLK_BLK_AON_UID_SYSREG_AON_IPCLKPORT_PCLK	0x205c
#define CLK_CON_GAT_CLK_BLK_AON_UID_TEST_WRAP_OTP_AON_IPCLKPORT_CLK	0x2060
#define CLK_CON_GAT_CLK_BLK_AON_UID_TMU_AON_IPCLKPORT_I_CLK	0x2064
#define CLK_CON_GAT_CLK_BLK_AON_UID_WDT0_TOP_IPCLKPORT_CLK	0x2068
#define CLK_CON_GAT_CLK_BLK_AON_UID_WDT0_TOP_IPCLKPORT_PCLK	0x206c
#define CLK_CON_GAT_CLK_BLK_AON_UID_WDT1_TOP_IPCLKPORT_CLK	0x2070
#define CLK_CON_GAT_CLK_BLK_AON_UID_WDT1_TOP_IPCLKPORT_PCLK	0x2074
#define CLK_CON_GAT_GOUT_BLK_AON_UID_APB_ASYNC_BRIDGE_TMU_AON_IPCLKPORT_PCLK	0x2078
#define CLK_CON_GAT_GOUT_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_SCAN_CLK_DST	0x207c
#define CLK_CON_GAT_GOUT_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_SCAN_CLK_ETC	0x2080
#define CLK_CON_GAT_GOUT_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_SCAN_CLK_DST	0x2084
#define CLK_CON_GAT_GOUT_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_SCAN_CLK_ETC	0x2088
#define CLK_CON_GAT_GOUT_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_SCAN_CLK_DST	0x208c
#define CLK_CON_GAT_GOUT_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_SCAN_CLK_ETC	0x2090
#define CLK_CON_GAT_GOUT_BLK_AON_UID_DAP_ABC_AON_IPCLKPORT_DAP_CLK	0x2094


/* List of registers in CMU_AON */
static const unsigned long aon_clk_regs[] = {
	PLL_LOCKTIME_PLL_AON,
	PLL_CON0_PLL_AON,
	PLL_CON1_PLL_AON,
	PLL_CON2_PLL_AON,
	PLL_CON4_PLL_AON,
	AON_CMU_AON_CONTROLLER_OPTION,
	CLKOUT_CON_BLK_AON_CMU_AON_CLKOUT0,
	CLKOUT_CON_BLK_AON_CMU_AON_CLKOUT1,
	CLK_CON_DIV_DIV4_PLLCLK,
	CLK_CON_DIV_DIV_OTP,
	CLK_CON_DIV_DIV_TMU,
	CLK_CON_DIV_PLL_AON_CLK,
	CLK_CON_DIV_SHARED_DIV_AON_PLL,
	CLK_CON_DIV_SHARED_DIV_MIF,
	CLK_CON_GAT_CLK_BLK_AON_UID_ABC_INTMEM_IPCLKPORT_ACLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_AON_CMU_AON_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_AON_SPI0_IPCLKPORT_I_AON_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_AON_UART_IPCLKPORT_I_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_AON_UART_IPCLKPORT_I_SCLK_UART,
	CLK_CON_GAT_CLK_BLK_AON_UID_AXI2APB_AON_IPCLKPORT_ACLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_CENTRAL_PMU_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_GPIO_ASYNCBR_TOP_AON_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_DCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_FCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_HCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_SCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_RAM_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_RAM_IPCLKPORT_HCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_ROM_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_ROM_IPCLKPORT_HCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_NIC_AON_IPCLKPORT_MAINCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_OTP_AON_IPCLKPORT_OSCCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_OTP_AON_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_SYSREG_AON_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_SYSREG_AON_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_TEST_WRAP_OTP_AON_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_TMU_AON_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_WDT0_TOP_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_WDT0_TOP_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_WDT1_TOP_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_AON_UID_WDT1_TOP_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_AON_UID_APB_ASYNC_BRIDGE_TMU_AON_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_AON_UID_DAP_ABC_AON_IPCLKPORT_DAP_CLK
};

/* PLL rate table for CMU_AON */
static const struct airbrush_pll_rate_table pll_aon_tbl[] = {
#ifdef CONFIG_B0
	PLL_F081XX_RATE(933000000, 146, 3, 0),
	PLL_F081XX_RATE(19200000, 288, 9, 5),
#endif
#ifdef CONFIG_A0
	PLL_F081XX_RATE(933000000, 243, 5, 0),
	PLL_F081XX_RATE(19200000, 288, 9, 5),
#endif
};

/* List of PLL clocks in CMU_AON */
static const struct airbrush_pll_clock aon_pll_clks[] = {
	PLL(pll_f0816x, FOUT_PLL_AON, "fout_pll_aon", "fin_pll_ab",
		PLL_LOCKTIME_PLL_AON, PLL_CON0_PLL_AON, pll_aon_tbl)
};

/* list of parent clocks for muxes in cmu_aon */
PNAME(mout_aon_aon_pll_p) = { "fin_pll_ab", "fout_pll_aon" };

/* List of mux clocks in CMU_AON */
static const struct airbrush_mux_clock aon_mux_clks[] = {
	MUX(MOUT_AON_PLL_AON, "mout_aon_pll_aon",
		mout_aon_aon_pll_p, PLL_CON0_PLL_AON, 4, 1),
};

/* List of div clocks in CMU_AON */
static const struct airbrush_div_clock aon_div_clks[] = {
	DIV(0, "dout_aon_div4_pllclk", "mout_aon_pll_aon", CLK_CON_DIV_DIV4_PLLCLK, 0, 4),
	DIV(0, "dout_aon_div_otp", "fin_pll_ab", CLK_CON_DIV_DIV_OTP, 0, 4),
	DIV(DOUT_AON_SHARED_DIV_AON_PLL, "dout_aon_shared_div_aon_pll", "mout_aon_pll_aon", CLK_CON_DIV_SHARED_DIV_AON_PLL, 0, 4),
	DIV(DOUT_AON_PLL_AON_CLK, "dout_aon_pll_aon_clk", "mout_aon_pll_aon", CLK_CON_DIV_PLL_AON_CLK, 0, 4),
	DIV(DOUT_AON_SHARED_DIV_MIF, "dout_aon_shared_div_mif", "mout_aon_pll_aon", CLK_CON_DIV_SHARED_DIV_MIF, 0, 4),
	DIV(0, "dout_aon_div_tmu", "fin_pll_ab", CLK_CON_DIV_DIV_TMU, 0, 4),
};

/* List of gate clocks in CMU_AON */
static const struct airbrush_gate_clock aon_gate_clks[] = {
	GATE(0, "clk_blk_aon_uid_aon_cmu_aon_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_AON_CMU_AON_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_abc_intmem_ipclkport_aclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_ABC_INTMEM_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_ram_ipclkport_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_RAM_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_rom_ipclkport_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_ROM_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_wdt1_top_ipclkport_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_WDT1_TOP_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_wdt1_top_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_WDT1_TOP_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_wdt0_top_ipclkport_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_WDT0_TOP_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_wdt0_top_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_WDT0_TOP_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_sysreg_aon_ipclkport_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_SYSREG_AON_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_sysreg_aon_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_SYSREG_AON_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_otp_aon_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_OTP_AON_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_nic_aon_ipclkport_mainclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_NIC_AON_IPCLKPORT_MAINCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_rom_ipclkport_hclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_ROM_IPCLKPORT_HCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_ram_ipclkport_hclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_RAM_IPCLKPORT_HCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_ipclkport_dclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_DCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_ipclkport_fclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_FCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_ipclkport_hclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_HCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_m0plus_ipclkport_sclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_M0PLUS_IPCLKPORT_SCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_gpio_asyncbr_top_aon_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_GPIO_ASYNCBR_TOP_AON_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_central_pmu_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_CENTRAL_PMU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_br_s_aon_ipclkport_i_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_BR_S_AON_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_br_intmem_ipclkport_i_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_BR_INTMEM_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_br_d_aon_ipclkport_i_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_BR_D_AON_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_axi2apb_aon_ipclkport_aclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_AXI2APB_AON_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_aon_uart_ipclkport_i_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_AON_UART_IPCLKPORT_I_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_aon_uart_ipclkport_i_sclk_uart", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_AON_UART_IPCLKPORT_I_SCLK_UART, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_aon_spi0_ipclkport_i_aon_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_CLK_BLK_AON_UID_AON_SPI0_IPCLKPORT_I_AON_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_aon_uid_dap_abc_aon_ipclkport_dap_clk", "dout_aon_div4_pllclk", CLK_CON_GAT_GOUT_BLK_AON_UID_DAP_ABC_AON_IPCLKPORT_DAP_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_aon_uid_apb_async_bridge_tmu_aon_ipclkport_pclk", "dout_aon_div4_pllclk", CLK_CON_GAT_GOUT_BLK_AON_UID_APB_ASYNC_BRIDGE_TMU_AON_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_test_wrap_otp_aon_ipclkport_clk", "dout_aon_div_otp", CLK_CON_GAT_CLK_BLK_AON_UID_TEST_WRAP_OTP_AON_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_aon_uid_tmu_aon_ipclkport_i_clk", "dout_aon_div_tmu", CLK_CON_GAT_CLK_BLK_AON_UID_TMU_AON_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
};


static const struct airbrush_cmu_info aon_cmu_info = {
	.pll_clks	= aon_pll_clks,
	.nr_pll_clks	= ARRAY_SIZE(aon_pll_clks),
	.mux_clks	= aon_mux_clks,
	.nr_mux_clks	= ARRAY_SIZE(aon_mux_clks),
	.div_clks	= aon_div_clks,
	.nr_div_clks	= ARRAY_SIZE(aon_div_clks),
	.gate_clks	= aon_gate_clks,
	.nr_gate_clks	= ARRAY_SIZE(aon_gate_clks),
	.nr_clk_ids	= AON_NR_CLK,
	.clk_regs	= aon_clk_regs,
	.nr_clk_regs	= ARRAY_SIZE(aon_clk_regs),
};

void abc_clk_aon_init(struct device_node *np)
{
	airbrush_cmu_register_one(np, &aon_cmu_info);
}
EXPORT_SYMBOL(abc_clk_aon_init);

/*******************CMU_CORE*****************************/
/* Register Offset definitions for CMU_CORE (0x10F10000) */
#define CORE_CMU_CORE_CONTROLLER_OPTION		0x800
#define CLKOUT_CON_BLK_CORE_CMU_CORE_CLKOUT0	0x810
#define CLKOUT_CON_BLK_CORE_CMU_CORE_CLKOUT1	0x814
#define CLK_CON_DIV_DIV2_PLLCLK_CORE	0x1800
#define CLK_CON_DIV_DIV4_PLLCLK_CORE	0x1804
#define CLK_CON_GAT_CLK_BLK_CORE_UID_CORE_CMU_CORE_IPCLKPORT_PCLK	0x2000
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_SCAN_CLK_DST	0x2004
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_SCAN_CLK_ETC	0x2008
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_SCAN_CLK_DST	0x200c
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_SCAN_CLK_ETC	0x2010
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST	0x2014
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC	0x2018
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST	0x201c
#define CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC	0x2020
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_SCAN_CLK_DST	0x2024
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_SCAN_CLK_ETC	0x2028
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST	0x202c
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC	0x2030
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_SCAN_CLK_DST	0x2034
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_SCAN_CLK_ETC	0x2038
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_SCAN_CLK_DST	0x203c
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_SCAN_CLK_ETC	0x2040
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST	0x2044
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC	0x2048
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST	0x204c
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC	0x2050
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_SCAN_CLK_DST	0x2054
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_SCAN_CLK_ETC	0x2058
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_SCAN_CLK_DST	0x205c
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_SCAN_CLK_ETC	0x2060
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_SCAN_CLK_DST	0x2064
#define CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_SCAN_CLK_ETC	0x2068
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_AXI2APB_CORE_IPCLKPORT_ACLK	0x206c
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_CLK	0x2070
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_CLK	0x2074
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_CLK	0x2078
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_CLK	0x207c
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_CONFIG_IPCLKPORT_MAINCLK	0x2080
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_CONFIG_IPCLKPORT_MAINCLK_R	0x2084
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_DMCCLK	0x2088
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_MAINCLK	0x208c
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_MAINCLK_R	0x2090
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_CONFIGCLK	0x2094
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_DMCCLK	0x2098
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_MAINCLK	0x209c
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_MAINCLK_R	0x20a0
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_DMCCLK	0x20a4
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_MAINCLK	0x20a8
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_MAINCLK_R	0x20ac
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_M_IPCLKPORT_ACLK	0x20b0
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_M_IPCLKPORT_PCLK	0x20b4
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_S_IPCLKPORT_ACLK	0x20b8
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_S_IPCLKPORT_PCLK	0x20bc
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUIPU_IPCLKPORT_ACLK	0x20c0
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUIPU_IPCLKPORT_PCLK	0x20c4
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUTPU_IPCLKPORT_ACLK	0x20c8
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUTPU_IPCLKPORT_PCLK	0x20cc
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_CLK	0x20d0
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_CLK	0x20d4
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_CLK	0x20d8
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_CLK	0x20dc
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_CLK	0x20e0
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_CLK	0x20e4
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_CLK	0x20e8
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_CLK	0x20ec
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_CLK	0x20f0
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SYSREG_CORE_IPCLKPORT_CLK	    0x20f4
#define CLK_CON_GAT_GOUT_BLK_CORE_UID_SYSREG_CORE_IPCLKPORT_PCLK	0x20f8

static const unsigned long core_clk_regs[] = {
	CORE_CMU_CORE_CONTROLLER_OPTION,
	CLKOUT_CON_BLK_CORE_CMU_CORE_CLKOUT0,
	CLKOUT_CON_BLK_CORE_CMU_CORE_CLKOUT1,
	CLK_CON_DIV_DIV2_PLLCLK_CORE,
	CLK_CON_DIV_DIV4_PLLCLK_CORE,
	CLK_CON_GAT_CLK_BLK_CORE_UID_CORE_CMU_CORE_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_CLK_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_AXI2APB_CORE_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_CONFIG_IPCLKPORT_MAINCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_CONFIG_IPCLKPORT_MAINCLK_R,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_DMCCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_MAINCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_MAINCLK_R,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_CONFIGCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_DMCCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_MAINCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_MAINCLK_R,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_DMCCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_MAINCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_MAINCLK_R,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_M_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_M_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_S_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_S_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUIPU_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUIPU_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUTPU_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUTPU_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SYSREG_CORE_IPCLKPORT_CLK,
	CLK_CON_GAT_GOUT_BLK_CORE_UID_SYSREG_CORE_IPCLKPORT_PCLK,
};

/* DIV Clocks */
static const struct airbrush_div_clock core_div_clks[] = {
	DIV(0, "dout_core_div2_pllclk_core", "dout_aon_pll_aon_clk", CLK_CON_DIV_DIV2_PLLCLK_CORE, 0, 4),
	DIV(0, "dout_core_div4_pllclk_core", "dout_core_div2_pllclk_core", CLK_CON_DIV_DIV4_PLLCLK_CORE, 0, 4),
};

/* GATE Clocks */
static const struct airbrush_gate_clock core_gate_clks[] = {
	GATE(0, "gout_blk_core_uid_nic400_primary_ipclkport_configclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_CONFIGCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_primary_ipclkport_dmcclk", "dout_core_div2_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_DMCCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_ipu_ipclkport_dmcclk", "dout_core_div2_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_DMCCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_tpu_ipclkport_dmcclk", "dout_core_div2_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_DMCCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_axi2apb_core_ipclkport_aclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_AXI2APB_CORE_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmuipu_ipclkport_pclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUIPU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmutpu_ipclkport_pclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUTPU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmufsys_m_ipclkport_pclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_M_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmufsys_s_ipclkport_pclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_S_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_sysreg_core_ipclkport_pclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SYSREG_CORE_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_sysreg_core_ipclkport_clk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SYSREG_CORE_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_ipu_ipclkport_mainclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_MAINCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_ipu_ipclkport_mainclk_r", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_IPU_IPCLKPORT_MAINCLK_R, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_primary_ipclkport_mainclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_MAINCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_primary_ipclkport_mainclk_r", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_PRIMARY_IPCLKPORT_MAINCLK_R, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_tpu_ipclkport_mainclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_MAINCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_tpu_ipclkport_mainclk_r", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_TPU_IPCLKPORT_MAINCLK_R, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_core_uid_core_cmu_core_ipclkport_pclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_CLK_BLK_CORE_UID_CORE_CMU_CORE_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_s_aon_cfg_ipclkport_i_clk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_AON_CFG_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_s_ipu_cfg_ipclkport_i_clk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_IPU_CFG_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_s_tpu_cfg_ipclkport_i_clk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_TPU_CFG_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_s_mif_cfg_ipclkport_i_clk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_MIF_CFG_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_config_ipclkport_mainclk", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_CONFIG_IPCLKPORT_MAINCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_nic400_config_ipclkport_mainclk_r", "dout_core_div4_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_NIC400_CONFIG_IPCLKPORT_MAINCLK_R, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_mi_blk_ipu_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_mi_blk_tpu_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_mi_d_aon_primary_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_D_AON_PRIMARY_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_mi_d_fsys_primary_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_MI_D_FSYS_PRIMARY_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_s_fsys_primary_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_FSYS_PRIMARY_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_s_intmem_primary_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_S_INTMEM_PRIMARY_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmufsys_m_ipclkport_aclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_M_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmufsys_s_ipclkport_aclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUFSYS_S_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmuipu_ipclkport_aclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUIPU_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_ppmutpu_ipclkport_aclk", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_CORE_UID_PPMUTPU_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_core_uid_mi_blk_ipu_ipclkport_i_scan_clk_dst", "dout_aon_pll_aon_clk", CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_SCAN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_core_uid_mi_blk_ipu_ipclkport_i_scan_clk_etc", "dout_aon_pll_aon_clk", CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_IPU_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_core_uid_mi_blk_tpu_ipclkport_i_scan_clk_dst", "dout_aon_pll_aon_clk", CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_SCAN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_core_uid_mi_blk_tpu_ipclkport_i_scan_clk_etc", "dout_aon_pll_aon_clk", CLK_CON_GAT_CLK_BLK_CORE_UID_MI_BLK_TPU_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_dmc0_ipu_ipclkport_i_clk", "dout_core_div2_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_IPU_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_dmc0_tpu_ipclkport_i_clk", "dout_core_div2_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_TPU_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_core_uid_si_dmc0_primary_ipclkport_i_clk", "dout_core_div2_pllclk_core", CLK_CON_GAT_GOUT_BLK_CORE_UID_SI_DMC0_PRIMARY_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
};

static const struct airbrush_cmu_info core_cmu_info = {
	.div_clks	= core_div_clks,
	.nr_div_clks	= ARRAY_SIZE(core_div_clks),
	.gate_clks	= core_gate_clks,
	.nr_gate_clks	= ARRAY_SIZE(core_gate_clks),
	.nr_clk_ids	= CORE_NR_CLK,
	.clk_regs	= core_clk_regs,
	.nr_clk_regs	= ARRAY_SIZE(core_clk_regs),
};

void abc_clk_core_init(struct device_node *np)
{
	airbrush_cmu_register_one(np, &core_cmu_info);
}
EXPORT_SYMBOL(abc_clk_core_init);

/***********************CMU_FSYS**************************/
/* Register Offset definitions for CMU_FSYS (0x10710000) */
#define FSYS_CMU_FSYS_CONTROLLER_OPTION	0x800
#define CLKOUT_CON_BLK_FSYS_CMU_FSYS_CLKOUT0	0x810
#define CLKOUT_CON_BLK_FSYS_CMU_FSYS_CLKOUT1	0x814
#define CLK_CON_DIV_DIV4_PLLCLK_FSYS	0x1804
#define CLK_CON_GAT_CLK_BLK_FSYS_UID_FSYS_CMU_FSYS_IPCLKPORT_PCLK	0x2000
#define CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_ABC_PCIE_SUB_CTRL_AUX_CLK_SOC	0x2004
#define CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_IMMORTAL_CLK	0x2008
#define CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_MSTR_ACLK_SOC	0x200c
#define CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_SLV_ACLK_SOC	0x2010
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_AXI2APB_FSYS_IPCLKPORT_ACLK	0x2014
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_BUS_S_FSYS_IPCLKPORT_MAINCLK	0x2018
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_CLK	0x201c
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_SCAN_CLK_DST	0x2020
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_SCAN_CLK_ETC	0x2024
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_CLK	0x2028
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_SCAN_CLK_ETC	0x202c
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_SCSN_CLK_DST	0x2030
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_ABC_PCIE_SUB_CTRL_I_DRIVER_APB_CLK	0x2034
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_DBI_ACLK_SOC	0x2038
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_APB_PCLK	0x203c
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_APB_PCLK_PCS	0x2040
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_LN0_APB_PCLK	0x2044
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_LN1_APB_PCLK	0x2048
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_PCS_HS_SCAN_CLK	0x204c
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_SYSREG_FSYS_IPCLKPORT_CLK		0x2050
#define CLK_CON_GAT_GOUT_BLK_FSYS_UID_SYSREG_FSYS_IPCLKPORT_PCLK	0x2054

static const unsigned long fsys_clk_regs[] = {
	FSYS_CMU_FSYS_CONTROLLER_OPTION,
	CLKOUT_CON_BLK_FSYS_CMU_FSYS_CLKOUT0,
	CLKOUT_CON_BLK_FSYS_CMU_FSYS_CLKOUT1,
	CLK_CON_DIV_DIV4_PLLCLK_FSYS,
	CLK_CON_GAT_CLK_BLK_FSYS_UID_FSYS_CMU_FSYS_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_ABC_PCIE_SUB_CTRL_AUX_CLK_SOC,
	CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_IMMORTAL_CLK,
	CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_MSTR_ACLK_SOC,
	CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_SLV_ACLK_SOC,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_AXI2APB_FSYS_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_BUS_S_FSYS_IPCLKPORT_MAINCLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_SCSN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_ABC_PCIE_SUB_CTRL_I_DRIVER_APB_CLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_DBI_ACLK_SOC,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_APB_PCLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_APB_PCLK_PCS,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_LN0_APB_PCLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_LN1_APB_PCLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_PCS_HS_SCAN_CLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_SYSREG_FSYS_IPCLKPORT_CLK,
	CLK_CON_GAT_GOUT_BLK_FSYS_UID_SYSREG_FSYS_IPCLKPORT_PCLK,
};


/* DIV Clocks */
static const struct airbrush_div_clock fsys_div_clks[]  = {
	DIV(0, "dout_fsys_div4_pllclk_fsys", "dout_aon_pll_aon_clk", CLK_CON_DIV_DIV4_PLLCLK_FSYS, 0, 4),
};

/* GATE Clocks */
static const struct airbrush_gate_clock fsys_gate_clks[] = {
	GATE(0,"gout_blk_fsys_uid_lh_mi_fsys_ipclkport_i_scan_clk_dst", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_SCAN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_lh_mi_fsys_ipclkport_i_scan_clk_etc", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_lh_si_fsys_ipclkport_i_scan_clk_etc", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_lh_si_fsys_ipclkport_i_scsn_clk_dst", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_SCSN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"clk_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_mstr_aclk_soc", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_MSTR_ACLK_SOC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_lh_mi_fsys_ipclkport_i_clk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_MI_FSYS_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_lh_si_fsys_ipclkport_i_clk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_LH_SI_FSYS_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_axi2apb_fsys_ipclkport_aclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_AXI2APB_FSYS_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_bus_s_fsys_ipclkport_mainclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_BUS_S_FSYS_IPCLKPORT_MAINCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_abc_pcie_sub_ctrl_i_driver_apb_clk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_ABC_PCIE_SUB_CTRL_I_DRIVER_APB_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_dbi_aclk_soc", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_DBI_ACLK_SOC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_i_apb_pclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_APB_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_i_apb_pclk_pcs", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_APB_PCLK_PCS, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_i_ln0_apb_pclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_LN0_APB_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_i_ln1_apb_pclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_LN1_APB_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_sysreg_fsys_ipclkport_clk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_SYSREG_FSYS_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_sysreg_fsys_ipclkport_pclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_SYSREG_FSYS_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"gout_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_i_pcs_hs_scan_clk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_GOUT_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_I_PCS_HS_SCAN_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"clk_blk_fsys_uid_pcie_mem_top_fsys_ipclkport_slv_aclk_soc", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_CLK_BLK_FSYS_UID_PCIE_MEM_TOP_FSYS_IPCLKPORT_SLV_ACLK_SOC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0,"clk_blk_fsys_uid_fsys_cmu_fsys_ipclkport_pclk", "dout_fsys_div4_pllclk_fsys", CLK_CON_GAT_CLK_BLK_FSYS_UID_FSYS_CMU_FSYS_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
};

static const struct airbrush_cmu_info fsys_cmu_info = {
	.div_clks	= fsys_div_clks,
	.nr_div_clks	= ARRAY_SIZE(fsys_div_clks),
	.gate_clks	= fsys_gate_clks,
	.nr_gate_clks	= ARRAY_SIZE(fsys_gate_clks),
	.nr_clk_ids	= FSYS_NR_CLK,
	.clk_regs	= fsys_clk_regs,
	.nr_clk_regs	= ARRAY_SIZE(fsys_clk_regs),
};

void abc_clk_fsys_init(struct device_node *np)
{
	airbrush_cmu_register_one(np, &fsys_cmu_info);
}
EXPORT_SYMBOL(abc_clk_fsys_init);

/*********************** CMU_IPU ************************/
/* Register Offset definitions for CMU_IPU (0x10240000) */
#define PLL_LOCKTIME_PLL_IPU	0x0
#define PLL_CON0_PLL_IPU	0x120
#define PLL_CON1_PLL_IPU	0x124
#define PLL_CON2_PLL_IPU	0x128
#define PLL_CON4_PLL_IPU	0x130
#define IPU_CMU_IPU_CONTROLLER_OPTION	0x800
#define CLKOUT_CON_BLK_IPU_CMU_IPU_CLKOUT0	0x810
#define CLKOUT_CON_BLK_IPU_CMU_IPU_CLKOUT1	0x814
#define CLK_CON_MUX_MOUT_AONCLK_PLLCLK1	0x1000
#define CLK_CON_DIV_DIV4_PLLCLK_IPU	0x1800
#define CLK_CON_DIV_IPU_PLL_CLK_DIV_1	0x1808
#define CLK_CON_BUF_IPU_CLK_INTEST	0x2000
#define CLK_CON_GAT_CLK_BLK_IPU_UID_AXI2APB_BRIDGE_IPU_IPCLKPORT_ACLK	0x2004
#define CLK_CON_GAT_CLK_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_CLK	0x2008
#define CLK_CON_GAT_CLK_BLK_IPU_UID_DFT_IPU_IPCLKPORT_IPU_CLK_INTEST	0x200c
#define CLK_CON_GAT_CLK_BLK_IPU_UID_HPM0_IPU_IPCLKPORT_HPM_TARGETCLK_C	0x2010
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_CLK	0x2014
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_CMU_IPU_IPCLKPORT_PCLK	0x2018
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_HPM_APBIF_IPCLKPORT_CLK	0x201c
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_HPM_APBIF_IPCLKPORT_PCLK	0x2020
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_APB	0x2024
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_AXI	0x2028
#define CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_IPU	0x202c
#define CLK_CON_GAT_CLK_BLK_IPU_UID_SYSREG_IPU_IPCLKPORT_CLK	0x2030
#define CLK_CON_GAT_CLK_BLK_IPU_UID_SYSREG_IPU_IPCLKPORT_PCLK	0x2034
#define CLK_CON_GAT_GOUT_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_SCAN_CLK_DST	0x2038
#define CLK_CON_GAT_GOUT_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_SCAN_CLK_ETC	0x203c
#define CLK_CON_GAT_GOUT_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_DST	0x2040
#define CLK_CON_GAT_GOUT_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_ETC	0x2044

static const unsigned long ipu_clk_regs[] = {
	PLL_LOCKTIME_PLL_IPU,
	PLL_CON0_PLL_IPU,
	PLL_CON1_PLL_IPU,
	PLL_CON2_PLL_IPU,
	PLL_CON4_PLL_IPU,
	IPU_CMU_IPU_CONTROLLER_OPTION,
	CLKOUT_CON_BLK_IPU_CMU_IPU_CLKOUT0,
	CLKOUT_CON_BLK_IPU_CMU_IPU_CLKOUT1,
	CLK_CON_MUX_MOUT_AONCLK_PLLCLK1,
	CLK_CON_DIV_DIV4_PLLCLK_IPU,
	CLK_CON_DIV_IPU_PLL_CLK_DIV_1,
	CLK_CON_BUF_IPU_CLK_INTEST,
	CLK_CON_GAT_CLK_BLK_IPU_UID_AXI2APB_BRIDGE_IPU_IPCLKPORT_ACLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_DFT_IPU_IPCLKPORT_IPU_CLK_INTEST,
	CLK_CON_GAT_CLK_BLK_IPU_UID_HPM0_IPU_IPCLKPORT_HPM_TARGETCLK_C,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_CMU_IPU_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_HPM_APBIF_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_HPM_APBIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_APB,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_AXI,
	CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_IPU,
	CLK_CON_GAT_CLK_BLK_IPU_UID_SYSREG_IPU_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_IPU_UID_SYSREG_IPU_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_ETC,
};

/* PLL rate table for CMU_IPU */
static const struct airbrush_pll_rate_table pll_ipu_tbl[] = {
#ifdef CONFIG_B0
	PLL_F081XX_RATE(850000000, 354, 2, 2),
	PLL_F081XX_RATE(680000000, 425, 3, 2),
	PLL_F081XX_RATE(544000000, 680, 3, 3),
	PLL_F081XX_RATE(408000000, 340, 2, 3),
	PLL_F081XX_RATE(272000000, 680, 3, 4),
	PLL_F081XX_RATE(50000000, 500, 3, 6),
	PLL_F081XX_RATE(19200000, 288, 9, 5),
#endif
#ifdef CONFIG_A0
	PLL_F081XX_RATE(610000000, 254, 2, 2),
	PLL_F081XX_RATE(578000000, 361, 3, 2),
	PLL_F081XX_RATE(550000000, 458, 2, 3),
	PLL_F081XX_RATE(440000000, 550, 3, 3),
	PLL_F081XX_RATE(330000000, 275, 2, 3),
	PLL_F081XX_RATE(220000000, 550, 3, 4),
	PLL_F081XX_RATE(50000000, 500, 3, 6),
	PLL_F081XX_RATE(19200000, 288, 9, 5),
#endif
};

/* PLL Clocks */
static const struct airbrush_pll_clock ipu_pll_clks[] = {
	PLL(pll_f0816x, FOUT_PLL_IPU, "fout_pll_ipu", "fin_pll_ab", PLL_LOCKTIME_PLL_IPU, PLL_CON0_PLL_IPU, pll_ipu_tbl)
};

/* list of parent clocks for muxes in cmu_ipu */
PNAME(mout_ipu_ipu_pll_p) = { "fin_pll_ab", "fout_pll_ipu" };
PNAME(mout_aonclk_pllclk1_p) = { "dout_aon_shared_div_aon_pll", "dout_ipu_ipu_pll_clk_div_1" };

/* PLL MUX Clocks*/
static const struct airbrush_mux_clock ipu_mux_clks[] = {
	MUX(MOUT_IPU_AONCLK_PLLCLK1, "mout_ipu_aonclk_pllclk1", mout_aonclk_pllclk1_p, CLK_CON_MUX_MOUT_AONCLK_PLLCLK1, 0, 1),
	MUX(MOUT_IPU_PLL_IPU, "mout_ipu_pll_ipu", mout_ipu_ipu_pll_p, PLL_CON0_PLL_IPU, 4, 1),
};

/* DIV Clocks */
static const struct airbrush_div_clock ipu_div_clks[] = {
	DIV(0, "dout_ipu_div4_pllclk_ipu", "dout_aon_pll_aon_clk", CLK_CON_DIV_DIV4_PLLCLK_IPU, 0, 4),
	DIV(DOUT_IPU_IPU_PLL_CLK_DIV_1, "dout_ipu_ipu_pll_clk_div_1", "mout_ipu_pll_ipu", CLK_CON_DIV_IPU_PLL_CLK_DIV_1, 0, 4),
};

/* GATE Clocks */
static const struct airbrush_gate_clock ipu_gate_clks[] = {
	GATE(0, "gout_blk_ipu_uid_ipu_2_core_lh_ipclkport_i_scan_clk_dst", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_ipu_uid_ipu_2_core_lh_ipclkport_i_scan_clk_etc", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED,0 ),
	GATE(0, "clk_blk_ipu_uid_hpm0_ipu_ipclkport_hpm_targetclk_c", "mout_ipu_aonclk_pllclk1", CLK_CON_GAT_CLK_BLK_IPU_UID_HPM0_IPU_IPCLKPORT_HPM_TARGETCLK_C, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_dft_ipu_ipclkport_ipu_clk_intest", "mout_ipu_aonclk_pllclk1", CLK_CON_GAT_CLK_BLK_IPU_UID_DFT_IPU_IPCLKPORT_IPU_CLK_INTEST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_IPU,
		"clk_blk_ipu_uid_ipu_ipclkport_clk_ipu",
		"mout_ipu_aonclk_pllclk1",
		CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_IPU, 21,
		CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_ipu_ipclkport_clk_axi", "dout_aon_pll_aon_clk", CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_AXI, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_ipu_ipclkport_clk_apb", "dout_ipu_div4_pllclk_ipu", CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_IPCLKPORT_CLK_APB, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_ipu_cmu_ipu_ipclkport_pclk", "dout_ipu_div4_pllclk_ipu", CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_CMU_IPU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_axi2apb_bridge_ipu_ipclkport_aclk", "dout_ipu_div4_pllclk_ipu", CLK_CON_GAT_CLK_BLK_IPU_UID_AXI2APB_BRIDGE_IPU_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_core_2_ipu_lh_ipclkport_i_clk", "dout_ipu_div4_pllclk_ipu", CLK_CON_GAT_CLK_BLK_IPU_UID_CORE_2_IPU_LH_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_ipu_2_core_lh_ipclkport_i_clk", "dout_aon_pll_aon_clk", CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_2_CORE_LH_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_ipu_hpm_apbif_ipclkport_pclk", "dout_ipu_div4_pllclk_ipu",  CLK_CON_GAT_CLK_BLK_IPU_UID_IPU_HPM_APBIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_sysreg_ipu_ipclkport_clk", "dout_ipu_div4_pllclk_ipu",  CLK_CON_GAT_CLK_BLK_IPU_UID_SYSREG_IPU_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_ipu_uid_sysreg_ipu_ipclkport_pclk", "dout_ipu_div4_pllclk_ipu",  CLK_CON_GAT_CLK_BLK_IPU_UID_SYSREG_IPU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
};

static const struct airbrush_cmu_info ipu_cmu_info = {
	.pll_clks	= ipu_pll_clks,
	.nr_pll_clks	= ARRAY_SIZE(ipu_pll_clks),
	.mux_clks	= ipu_mux_clks,
	.nr_mux_clks	= ARRAY_SIZE(ipu_mux_clks),
	.div_clks	= ipu_div_clks,
	.nr_div_clks	= ARRAY_SIZE(ipu_div_clks),
	.gate_clks	= ipu_gate_clks,
	.nr_gate_clks	= ARRAY_SIZE(ipu_gate_clks),
	.nr_clk_ids	= IPU_NR_CLK,
	.clk_regs	= ipu_clk_regs,
	.nr_clk_regs	= ARRAY_SIZE(ipu_clk_regs),
};

void abc_clk_ipu_init(struct device_node *np)
{
	airbrush_cmu_register_one(np, &ipu_cmu_info);
}
EXPORT_SYMBOL(abc_clk_ipu_init);

/*********************** CMU_MIF ************************/
/* Register Offset definitions for CMU_MIF (0x10510000) */
#define PLL_LOCKTIME_PLL_PHY_MIF	0x8
#define PLL_CON0_PLL_PHY_MIF	0x140
#define PLL_CON1_PLL_PHY_MIF	0x144
#define PLL_CON2_PLL_PHY_MIF	0x148
#define PLL_CON4_PLL_PHY_MIF	0x150
#define MIF_CMU_MIF_CONTROLLER_OPTION	0x800
#define CLKOUT_CON_BLK_MIF_CMU_MIF_CLKOUT0	0x810
#define CLKOUT_CON_BLK_MIF_CMU_MIF_CLKOUT1	0x814
#define CLK_CON_DIV_DFI_DIV2	0x1800
#define CLK_CON_DIV_DIV2_PLLCLK_MIF	0x1804
#define CLK_CON_DIV_DIV4_PLLCLK_MIF	0x1808
#define CLK_CON_GAT_CLK_BLK_MIF_UID_MIF_CMU_MIF_IPCLKPORT_PCLK	0x2000
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI2APB_MIF_IPCLKPORT_ACLK	0x2004
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_CLK	0x2008
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_SCAN_CLK_DST	0x200c
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_SCAN_CLK_ETC	0x2010
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_IPU_MIF_IPCLKPORT_I_SCAN_CLK_DST	0x2014
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_IPU_MIF_IPCLKPORT_I_SCAN_CLK_ETC	0x2018
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_PCIE_MIF_IPCLKPORT_I_SCAN_CLK_DST	0x201c
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_PCIE_MIF_IPCLKPORT_I_SCAN_CLK_ETC	0x2020
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_TPU_MIF_IPCLKPORT_I_SCAN_CLK_DST	0x2024
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_TPU_MIF_IPCLKPORT_I_SCAN_CLK_ETC	0x2028
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_PCLK	0x202c
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_PCLK_TZ	0x2030
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_RCLK	0x2034
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_PHY0_MIF_IPCLKPORT_PCLK	0x2038
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_PHY1_MIF_IPCLKPORT_PCLK	0x203c
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_PLL_WRP_PHY_MIF_IPCLKPORT_CLK_USER	0x2040
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_PPC_MIF_IPCLKPORT_PCLK	0x2044
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_SYSREG_MIF_IPCLKPORT_CLK	0x2048
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_SYSREG_MIF_IPCLKPORT_PCLK	0x204c
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_VT_MON_MIF_IPCLKPORT_OSC_CLK_24M	0x2050
#define CLK_CON_GAT_GOUT_BLK_MIF_UID_VT_MON_MIF_IPCLKPORT_PCLK	0x2054

static const unsigned long mif_clk_regs[] = {
	PLL_LOCKTIME_PLL_PHY_MIF,
	PLL_CON0_PLL_PHY_MIF,
	PLL_CON1_PLL_PHY_MIF,
	PLL_CON2_PLL_PHY_MIF,
	PLL_CON4_PLL_PHY_MIF,
	MIF_CMU_MIF_CONTROLLER_OPTION,
	CLKOUT_CON_BLK_MIF_CMU_MIF_CLKOUT0,
	CLKOUT_CON_BLK_MIF_CMU_MIF_CLKOUT1,
	CLK_CON_DIV_DFI_DIV2,
	CLK_CON_DIV_DIV2_PLLCLK_MIF,
	CLK_CON_DIV_DIV4_PLLCLK_MIF,
	CLK_CON_GAT_CLK_BLK_MIF_UID_MIF_CMU_MIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI2APB_MIF_IPCLKPORT_ACLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_CLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_IPU_MIF_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_IPU_MIF_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_PCIE_MIF_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_PCIE_MIF_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_TPU_MIF_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_TPU_MIF_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_PCLK_TZ,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_PHY0_MIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_PHY1_MIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_PLL_WRP_PHY_MIF_IPCLKPORT_CLK_USER,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_PPC_MIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_SYSREG_MIF_IPCLKPORT_CLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_SYSREG_MIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_VT_MON_MIF_IPCLKPORT_OSC_CLK_24M,
	CLK_CON_GAT_GOUT_BLK_MIF_UID_VT_MON_MIF_IPCLKPORT_PCLK,
};

/* FIXEDRATE Clocks */
static const struct airbrush_fixed_rate_clock mif_fixed_clks[] = {
	FRATE(0, "clk_dfi", NULL, 0, 466134002),
};

/* PLL rate table for CMU_MIF */
static const struct airbrush_pll_rate_table pll_mif_tbl[] = {
#ifdef CONFIG_B0
	PLL_F081XX_RATE(3733000000, 778, 4, 0),
	PLL_F081XX_RATE(1866000000, 778, 4, 1),
#endif
#ifdef CONFIG_A0
	PLL_F081XX_RATE(3733000000, 583, 3, 0),
	PLL_F081XX_RATE(1864000000, 777, 4, 1),
#endif
};


/* PLL Clocks */
static const struct airbrush_pll_clock mif_pll_clks[] = {
	PLL(pll_f0816x, 0, "fout_pll_phy_mif", "fin_pll_ab", PLL_LOCKTIME_PLL_PHY_MIF, PLL_CON0_PLL_PHY_MIF, pll_mif_tbl),
};

/* list of parent clocks for muxes in cmu_mif */
PNAME(mout_mif_phy_mif_pll_p) = { "fin_pll_ab", "fout_pll_phy_mif" };

/* PLL MUX Clocks*/
static const struct airbrush_mux_clock mif_mux_clks[] = {
	MUX(0, "mout_mif_pll_phy_mif", mout_mif_phy_mif_pll_p, PLL_CON0_PLL_PHY_MIF, 4, 1),
};

/* DIV Clocks */
static const struct airbrush_div_clock mif_div_clks[] = {
	DIV(0, "dout_mif_dfi_div2", "clk_dfi", CLK_CON_DIV_DFI_DIV2, 0, 4),
	DIV(0, "dout_mif_div4_pllclk_mif", "dout_mif_div2_pllclk_mif", CLK_CON_DIV_DIV4_PLLCLK_MIF, 0, 4),
	DIV(0, "dout_mif_div2_pllclk_mif", "dout_aon_pll_aon_clk", CLK_CON_DIV_DIV2_PLLCLK_MIF, 0, 4),
};

/* GATE Clocks */
static const struct airbrush_gate_clock mif_gate_clks[] = {
	GATE(0, "gout_blk_mif_uid_axi2apb_mif_ipclkport_aclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI2APB_MIF_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_phy0_mif_ipclkport_pclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_PHY0_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_phy1_mif_ipclkport_pclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_PHY1_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_ppc_mif_ipclkport_pclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_PPC_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_sysreg_mif_ipclkport_pclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_SYSREG_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_axi_async_br_axi2apb_mif_ipclkport_i_clk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_axi_async_br_axi2apb_mif_ipclkport_i_scan_clk_dst", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_SCAN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_axi_async_br_axi2apb_mif_ipclkport_i_scan_clk_etc", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_AXI_ASYNC_BR_AXI2APB_MIF_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_sysreg_mif_ipclkport_clk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_SYSREG_MIF_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_mif_uid_mif_cmu_mif_ipclkport_pclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_CLK_BLK_MIF_UID_MIF_CMU_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_vt_mon_mif_ipclkport_pclk", "dout_mif_div4_pllclk_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_VT_MON_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_pll_wrp_phy_mif_ipclkport_clk_user", "dout_aon_shared_div_mif", CLK_CON_GAT_GOUT_BLK_MIF_UID_PLL_WRP_PHY_MIF_IPCLKPORT_CLK_USER, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_dmc_mif_ipclkport_pclk", "dout_mif_dfi_div2", CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_dmc_mif_ipclkport_pclk_tz", "dout_mif_dfi_div2", CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_PCLK_TZ, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_mif_uid_dmc_mif_ipclkport_rclk", "dout_mif_dfi_div2", CLK_CON_GAT_GOUT_BLK_MIF_UID_DMC_MIF_IPCLKPORT_RCLK, 21, CLK_IGNORE_UNUSED, 0),
};

static const struct airbrush_cmu_info mif_cmu_info = {
	.pll_clks	= mif_pll_clks,
	.nr_pll_clks	= ARRAY_SIZE(mif_pll_clks),
	.mux_clks	= mif_mux_clks,
	.nr_mux_clks	= ARRAY_SIZE(mif_mux_clks),
	.div_clks	= mif_div_clks,
	.nr_div_clks	= ARRAY_SIZE(mif_div_clks),
	.gate_clks	= mif_gate_clks,
	.nr_gate_clks	= ARRAY_SIZE(mif_gate_clks),
	.fixed_clks	= mif_fixed_clks,
	.nr_fixed_clks	= ARRAY_SIZE(mif_fixed_clks),
	.nr_clk_ids	= MIF_NR_CLK,
	.clk_regs	= mif_clk_regs,
	.nr_clk_regs	= ARRAY_SIZE(mif_clk_regs),
};

void abc_clk_mif_init(struct device_node *np)
{
	airbrush_cmu_register_one(np, &mif_cmu_info);
}
EXPORT_SYMBOL(abc_clk_mif_init);

/************************ CMU_TPU ***********************/
/* Register Offset definitions for CMU_TPU (0x10040000) */
#define PLL_LOCKTIME_PLL_TPU	0x0
#define PLL_CON0_PLL_TPU	0x120
#define PLL_CON1_PLL_TPU	0x124
#define PLL_CON2_PLL_TPU	0x128
#define PLL_CON4_PLL_TPU	0x130
#define TPU_CMU_TPU_CONTROLLER_OPTION	0x800
#define CLKOUT_CON_BLK_TPU_CMU_TPU_CLKOUT0	0x810
#define CLKOUT_CON_BLK_TPU_CMU_TPU_CLKOUT1	0x814
#define CLK_CON_MUX_MOUT_TPU_AONCLK_PLLCLK	0x1000
#define CLK_CON_DIV_DIV4_PLLCLK_TPU	0x1800
#define CLK_CON_DIV_TPU_PLL_DIV_CLK_1	0x1814
#define CLK_CON_BUF_TPU_CLK_INTEST	0x2000
#define CLK_CON_GAT_CLK_BLK_TPU_UID_AXI2APB_BRIDGE_TPU_IPCLKPORT_ACLK	0x2004
#define CLK_CON_GAT_CLK_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_CLK	0x2008
#define CLK_CON_GAT_CLK_BLK_TPU_UID_DFT_TPU_IPCLKPORT_TPU_CLK_INTEST	0x200c
#define CLK_CON_GAT_CLK_BLK_TPU_UID_HPM0_TPU_IPCLKPORT_HPM_TARGETCLK_C	0x2010
#define CLK_CON_GAT_CLK_BLK_TPU_UID_SYSREG_TPU_IPCLKPORT_CLK	0x2014
#define CLK_CON_GAT_CLK_BLK_TPU_UID_SYSREG_TPU_IPCLKPORT_PCLK	0x2018
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_CLK	0x201c
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_CMU_TPU_IPCLKPORT_PCLK	0x2020
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_HPM_APBIF_IPCLKPORT_CLK	0x2024
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_HPM_APBIF_IPCLKPORT_PCLK	0x2028
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_APB_PCLK	0x202c
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_AXI_CLK	0x2030
#define CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_CLK_TPU	0x2034
#define CLK_CON_GAT_GOUT_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_SCAN_CLK_DST	0x2038
#define CLK_CON_GAT_GOUT_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_SCAN_CLK_ETC	0x203c
#define CLK_CON_GAT_GOUT_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_DST	0x2040
#define CLK_CON_GAT_GOUT_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_ETC	0x2044

static const unsigned long tpu_clk_regs[] = {
	PLL_LOCKTIME_PLL_TPU,
	PLL_CON0_PLL_TPU,
	PLL_CON1_PLL_TPU,
	PLL_CON2_PLL_TPU,
	PLL_CON4_PLL_TPU,
	TPU_CMU_TPU_CONTROLLER_OPTION,
	CLKOUT_CON_BLK_TPU_CMU_TPU_CLKOUT0,
	CLKOUT_CON_BLK_TPU_CMU_TPU_CLKOUT1,
	CLK_CON_MUX_MOUT_TPU_AONCLK_PLLCLK,
	CLK_CON_DIV_DIV4_PLLCLK_TPU,
	CLK_CON_DIV_TPU_PLL_DIV_CLK_1,
	CLK_CON_BUF_TPU_CLK_INTEST,
	CLK_CON_GAT_CLK_BLK_TPU_UID_AXI2APB_BRIDGE_TPU_IPCLKPORT_ACLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_DFT_TPU_IPCLKPORT_TPU_CLK_INTEST,
	CLK_CON_GAT_CLK_BLK_TPU_UID_HPM0_TPU_IPCLKPORT_HPM_TARGETCLK_C,
	CLK_CON_GAT_CLK_BLK_TPU_UID_SYSREG_TPU_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_SYSREG_TPU_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_CLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_CMU_TPU_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_HPM_APBIF_IPCLKPORT_CLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_HPM_APBIF_IPCLKPORT_PCLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_APB_PCLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_AXI_CLK,
	CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_CLK_TPU,
	CLK_CON_GAT_GOUT_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_SCAN_CLK_ETC,
	CLK_CON_GAT_GOUT_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_DST,
	CLK_CON_GAT_GOUT_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_ETC,
};

/* PLL rate table for CMU_TPU */
static const struct airbrush_pll_rate_table pll_tpu_tbl[] = {
#ifdef CONFIG_B0
	PLL_F081XX_RATE(1000000000, 625, 3, 2),
	PLL_F081XX_RATE(790000000, 329, 2, 2),
	PLL_F081XX_RATE(625000000, 260, 2, 2),
	PLL_F081XX_RATE(468000000, 390, 2, 3),
	PLL_F081XX_RATE(312000000, 260, 2, 3),
	PLL_F081XX_RATE(50000000, 500, 3, 6),
	PLL_F081XX_RATE(19200000, 288, 9, 5),
#endif
#ifdef CONFIG_A0
	PLL_F081XX_RATE(962000000, 601, 3, 2),
	PLL_F081XX_RATE(766000000, 319, 2, 2),
	PLL_F081XX_RATE(606000000, 505, 2, 3),
	PLL_F081XX_RATE(454000000, 378, 2, 3),
	PLL_F081XX_RATE(303000000, 505, 2, 4),
	PLL_F081XX_RATE(50000000, 500, 3, 6),
	PLL_F081XX_RATE(19200000, 288, 9, 5),
#endif
};

/* PLL Clocks*/
static const struct airbrush_pll_clock tpu_pll_clks[] = {
	PLL(pll_f0816x, FOUT_PLL_TPU, "fout_pll_tpu", "fin_pll_ab", PLL_LOCKTIME_PLL_TPU, PLL_CON0_PLL_TPU, pll_tpu_tbl),
};

/* list of parent clocks for muxes in cmu_mif */
PNAME(mout_tpu_tpu_pll_p) = { "fin_pll_ab", "fout_pll_tpu" };
PNAME(mout_tpu_aonclk_pllclk_p) = { "dout_aon_shared_div_aon_pll", "dout_tpu_tpu_pll_div_clk_1" };

/* MUX Clocks*/
static const struct airbrush_mux_clock tpu_mux_clks[] = {
	MUX(MOUT_TPU_AONCLK_PLLCLK, "mout_tpu_aonclk_pllclk", mout_tpu_aonclk_pllclk_p, CLK_CON_MUX_MOUT_TPU_AONCLK_PLLCLK, 0, 1),
	MUX(MOUT_TPU_PLL_TPU, "mout_tpu_pll_tpu", mout_tpu_tpu_pll_p, PLL_CON0_PLL_TPU, 4, 1),
};

/* DIV Clocks*/
static const struct airbrush_div_clock tpu_div_clks[] = {
	DIV(0, "dout_tpu_div4_pllclk_tpu", "dout_aon_pll_aon_clk", CLK_CON_DIV_DIV4_PLLCLK_TPU, 0, 4),
	DIV(DOUT_TPU_TPU_PLL_DIV_CLK_1, "dout_tpu_tpu_pll_div_clk_1", "mout_tpu_pll_tpu", CLK_CON_DIV_TPU_PLL_DIV_CLK_1, 0, 4),
};

/* GATE Clocks*/
static const struct airbrush_gate_clock tpu_gate_clks[] = {
	GATE(0, "gout_blk_tpu_uid_tpu_2_core_lh_ipclkport_i_scan_clk_dst", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_DST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "gout_blk_tpu_uid_tpu_2_core_lh_ipclkport_i_scan_clk_etc", "dout_aon_pll_aon_clk", CLK_CON_GAT_GOUT_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_SCAN_CLK_ETC, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_dft_tpu_ipclkport_tpu_clk_intest", "mout_tpu_aonclk_pllclk", CLK_CON_GAT_CLK_BLK_TPU_UID_DFT_TPU_IPCLKPORT_TPU_CLK_INTEST, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_hpm0_tpu_ipclkport_hpm_targetclk_c", "mout_tpu_aonclk_pllclk", CLK_CON_GAT_CLK_BLK_TPU_UID_HPM0_TPU_IPCLKPORT_HPM_TARGETCLK_C, 21, CLK_IGNORE_UNUSED, 0),
	GATE(CLK_BLK_TPU_UID_TPU_IPCLKPORT_CLK_TPU,
			"clk_blk_tpu_uid_tpu_ipclkport_clk_tpu",
			"mout_tpu_aonclk_pllclk",
			CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_CLK_TPU, 21,
			CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_tpu_ipclkport_axi_clk", "dout_aon_pll_aon_clk",  CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_AXI_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_tpu_ipclkport_apb_pclk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_IPCLKPORT_APB_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_tpu_cmu_tpu_ipclkport_pclk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_CMU_TPU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_axi2apb_bridge_tpu_ipclkport_aclk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_AXI2APB_BRIDGE_TPU_IPCLKPORT_ACLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_core_2_tpu_lh_ipclkport_i_clk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_CORE_2_TPU_LH_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_sysreg_tpu_ipclkport_clk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_SYSREG_TPU_IPCLKPORT_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_sysreg_tpu_ipclkport_pclk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_SYSREG_TPU_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_tpu_2_core_lh_ipclkport_i_clk", "dout_aon_pll_aon_clk",  CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_2_CORE_LH_IPCLKPORT_I_CLK, 21, CLK_IGNORE_UNUSED, 0),
	GATE(0, "clk_blk_tpu_uid_tpu_hpm_apbif_ipclkport_pclk", "dout_ipu_div4_pllclk_tpu",  CLK_CON_GAT_CLK_BLK_TPU_UID_TPU_HPM_APBIF_IPCLKPORT_PCLK, 21, CLK_IGNORE_UNUSED, 0),
};

static const struct airbrush_cmu_info tpu_cmu_info = {
	.pll_clks	= tpu_pll_clks,
	.nr_pll_clks	= ARRAY_SIZE(tpu_pll_clks),
	.mux_clks	= tpu_mux_clks,
	.nr_mux_clks	= ARRAY_SIZE(tpu_mux_clks),
	.div_clks	= tpu_div_clks,
	.nr_div_clks	= ARRAY_SIZE(tpu_div_clks),
	.gate_clks	= tpu_gate_clks,
	.nr_gate_clks	= ARRAY_SIZE(tpu_gate_clks),
	.nr_clk_ids	= TPU_NR_CLK,
	.clk_regs	= tpu_clk_regs,
	.nr_clk_regs	= ARRAY_SIZE(tpu_clk_regs),
};

void abc_clk_tpu_init(struct device_node *np)
{
	airbrush_cmu_register_one(np, &tpu_cmu_info);
}
EXPORT_SYMBOL(abc_clk_tpu_init);
