dtb-$(CONFIG_ARCH_GOOG_POLARIS) += polaris-p1.dtb
dtb-$(CONFIG_ARCH_GOOG_POLARIS) += polaris-p2.dtb
dtb-$(CONFIG_ARCH_GOOG_POLARIS) += apq8998-polaris-ver2.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
