#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_upgrade_ft3267.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_upgrade_test.o
