#
# Makefile for MNH PCIE/DMA devices
#

obj-$(CONFIG_MNH_PCIE_HOST) += mnh-pcie.o
obj-$(CONFIG_MNH_SM_HOST) += mnh-sm.o mnh-sm-ion.o mnh-pwr.o mnh-mipi.o mnh-ddr.o mnh-clk.o
obj-$(CONFIG_MNH_THERMAL_HOST) += mnh-thermal.o mnh-efuse.o
