/* auto generated: Monday, August 15th, 2016 12:26:47pm */
/* gucheng: edit 11/07/2018 for checkpatch */
/*
 * Copyright (c) 2016, Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of Intel nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __MNH_HWIO_CPU_
#define __MNH_HWIO_CPU_

#define HWIO_CPU_CFG_REGOFF 0x0
#define HWIO_CPU_CFG_ADDR(bAddr, regX) (bAddr + HWIO_CPU_CFG_REGOFF)
#define HWIO_CPU_CFG_CLUSTERIDAFF2_FLDMASK (0xff000000)
#define HWIO_CPU_CFG_CLUSTERIDAFF2_FLDSHFT (24)
#define HWIO_CPU_CFG_CLUSTERIDAFF1_FLDMASK (0xff0000)
#define HWIO_CPU_CFG_CLUSTERIDAFF1_FLDSHFT (16)
#define HWIO_CPU_CFG_RSVD0_FLDMASK (0xfff0)
#define HWIO_CPU_CFG_RSVD0_FLDSHFT (4)
#define HWIO_CPU_CFG_VINITHI_FLDMASK (0x8)
#define HWIO_CPU_CFG_VINITHI_FLDSHFT (3)
#define HWIO_CPU_CFG_CFGTE_FLDMASK (0x4)
#define HWIO_CPU_CFG_CFGTE_FLDSHFT (2)
#define HWIO_CPU_CFG_CFGEND_FLDMASK (0x2)
#define HWIO_CPU_CFG_CFGEND_FLDSHFT (1)
#define HWIO_CPU_CFG_AA64nAA32_FLDMASK (0x1)
#define HWIO_CPU_CFG_AA64nAA32_FLDSHFT (0)

#define HWIO_CPU_RST_CFG_REGOFF 0x4
#define HWIO_CPU_RST_CFG_ADDR(bAddr, regX) (bAddr + HWIO_CPU_RST_CFG_REGOFF)
#define HWIO_CPU_RST_CFG_RSVD0_FLDMASK (0xfffffffc)
#define HWIO_CPU_RST_CFG_RSVD0_FLDSHFT (2)
#define HWIO_CPU_RST_CFG_DBGL1RSTDISABLE_FLDMASK (0x2)
#define HWIO_CPU_RST_CFG_DBGL1RSTDISABLE_FLDSHFT (1)
#define HWIO_CPU_RST_CFG_L2RSTDISABLE_FLDMASK (0x1)
#define HWIO_CPU_RST_CFG_L2RSTDISABLE_FLDSHFT (0)

#define HWIO_CPU_RST_STS_REGOFF 0x8
#define HWIO_CPU_RST_STS_ADDR(bAddr, regX) (bAddr + HWIO_CPU_RST_STS_REGOFF)
#define HWIO_CPU_RST_STS_RSVD0_FLDMASK (0xfffffffc)
#define HWIO_CPU_RST_STS_RSVD0_FLDSHFT (2)
#define HWIO_CPU_RST_STS_DBGRSTREQ_FLDMASK (0x2)
#define HWIO_CPU_RST_STS_DBGRSTREQ_FLDSHFT (1)
#define HWIO_CPU_RST_STS_WARMRSTREQ_FLDMASK (0x1)
#define HWIO_CPU_RST_STS_WARMRSTREQ_FLDSHFT (0)

#define HWIO_CPU_PWR_MGMT_CFG_REGOFF 0x0C
#define HWIO_CPU_PWR_MGMT_CFG_ADDR(bAddr, regX) \
			(bAddr + HWIO_CPU_PWR_MGMT_CFG_REGOFF)
#define HWIO_CPU_PWR_MGMT_CFG_RSVD0_FLDMASK (0xfffffffc)
#define HWIO_CPU_PWR_MGMT_CFG_RSVD0_FLDSHFT (2)
#define HWIO_CPU_PWR_MGMT_CFG_L2FLUSHREQ_FLDMASK (0x2)
#define HWIO_CPU_PWR_MGMT_CFG_L2FLUSHREQ_FLDSHFT (1)
#define HWIO_CPU_PWR_MGMT_CFG_EVENTI_FLDMASK (0x1)
#define HWIO_CPU_PWR_MGMT_CFG_EVENTI_FLDSHFT (0)

#define HWIO_CPU_PWR_MGMT_STS_REGOFF 0x10
#define HWIO_CPU_PWR_MGMT_STS_ADDR(bAddr, regX) \
			(bAddr + HWIO_CPU_PWR_MGMT_STS_REGOFF)
#define HWIO_CPU_PWR_MGMT_STS_RSVD0_FLDMASK (0xffffff00)
#define HWIO_CPU_PWR_MGMT_STS_RSVD0_FLDSHFT (8)
#define HWIO_CPU_PWR_MGMT_STS_CPUQACTIVE_FLDMASK (0x80)
#define HWIO_CPU_PWR_MGMT_STS_CPUQACTIVE_FLDSHFT (7)
#define HWIO_CPU_PWR_MGMT_STS_DBGPWRUPREQ_FLDMASK (0x40)
#define HWIO_CPU_PWR_MGMT_STS_DBGPWRUPREQ_FLDSHFT (6)
#define HWIO_CPU_PWR_MGMT_STS_DBGNOPWRDWN_FLDMASK (0x20)
#define HWIO_CPU_PWR_MGMT_STS_DBGNOPWRDWN_FLDSHFT (5)
#define HWIO_CPU_PWR_MGMT_STS_SMPEN_FLDMASK (0x10)
#define HWIO_CPU_PWR_MGMT_STS_SMPEN_FLDSHFT (4)
#define HWIO_CPU_PWR_MGMT_STS_L2FLUSHDONE_FLDMASK (0x8)
#define HWIO_CPU_PWR_MGMT_STS_L2FLUSHDONE_FLDSHFT (3)
#define HWIO_CPU_PWR_MGMT_STS_STANDBYWFE_FLDMASK (0x4)
#define HWIO_CPU_PWR_MGMT_STS_STANDBYWFE_FLDSHFT (2)
#define HWIO_CPU_PWR_MGMT_STS_STANDBYWFI_FLDMASK (0x2)
#define HWIO_CPU_PWR_MGMT_STS_STANDBYWFI_FLDSHFT (1)
#define HWIO_CPU_PWR_MGMT_STS_EVENTO_FLDMASK (0x1)
#define HWIO_CPU_PWR_MGMT_STS_EVENTO_FLDSHFT (0)

#define HWIO_CPU_DBG_CFG_REGOFF 0x14
#define HWIO_CPU_DBG_CFG_ADDR(bAddr, regX) (bAddr + HWIO_CPU_DBG_CFG_REGOFF)
#define HWIO_CPU_DBG_CFG_RSVD0_FLDMASK (0xfffffffc)
#define HWIO_CPU_DBG_CFG_RSVD0_FLDSHFT (2)
#define HWIO_CPU_DBG_CFG_NIDEN_FLDMASK (0x2)
#define HWIO_CPU_DBG_CFG_NIDEN_FLDSHFT (1)
#define HWIO_CPU_DBG_CFG_DBGEN_FLDMASK (0x1)
#define HWIO_CPU_DBG_CFG_DBGEN_FLDSHFT (0)

#define HWIO_CPU_STS_REGOFF 0x18
#define HWIO_CPU_STS_ADDR(bAddr, regX) (bAddr + HWIO_CPU_STS_REGOFF)
#define HWIO_CPU_STS_STATUS_FLDMASK (0xffffffff)
#define HWIO_CPU_STS_STATUS_FLDSHFT (0)

#define HWIO_CPU_SECURE_REGOFF 0x1C
#define HWIO_CPU_SECURE_ADDR(bAddr, regX) (bAddr + HWIO_CPU_SECURE_REGOFF)
#define HWIO_CPU_SECURE_SECURE_LOCK_FLDMASK (0x80000000)
#define HWIO_CPU_SECURE_SECURE_LOCK_FLDSHFT (31)
#define HWIO_CPU_SECURE_RSVD0_FLDMASK (0x7ffffff8)
#define HWIO_CPU_SECURE_RSVD0_FLDSHFT (3)
#define HWIO_CPU_SECURE_CP15SDISABLE_FLDMASK (0x4)
#define HWIO_CPU_SECURE_CP15SDISABLE_FLDSHFT (2)
#define HWIO_CPU_SECURE_SPNIDEN_FLDMASK (0x2)
#define HWIO_CPU_SECURE_SPNIDEN_FLDSHFT (1)
#define HWIO_CPU_SECURE_SPIDEN_FLDMASK (0x1)
#define HWIO_CPU_SECURE_SPIDEN_FLDSHFT (0)

#define HWIO_CPU_DBG_BUS_REGOFF 0x20
#define HWIO_CPU_DBG_BUS_ADDR(bAddr, regX) (bAddr + HWIO_CPU_DBG_BUS_REGOFF)
#define HWIO_CPU_DBG_BUS_RSVD0_FLDMASK (0xfffffffc)
#define HWIO_CPU_DBG_BUS_RSVD0_FLDSHFT (2)
#define HWIO_CPU_DBG_BUS_DBG_MUX_SEL_FLDMASK (0x3)
#define HWIO_CPU_DBG_BUS_DBG_MUX_SEL_FLDSHFT (0)

#endif /* __MNH_HWIO_CPU_ */
