/* auto generated: Monday, August 15th, 2016 12:26:49pm */
/*
 * Copyright (c) 2016, Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of Intel nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __MNH_HWIO_MIPI_TX_
#define __MNH_HWIO_MIPI_TX_

#define HWIO_MIPI_TX_VERSION_REGOFF 0x0
#define HWIO_MIPI_TX_VERSION_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VERSION_REGOFF)
#define HWIO_MIPI_TX_VERSION_VERSION_FLDMASK (0xffffffff)
#define HWIO_MIPI_TX_VERSION_VERSION_FLDSHFT (0)

#define HWIO_MIPI_TX_CSI2_RESETN_REGOFF 0x4
#define HWIO_MIPI_TX_CSI2_RESETN_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_CSI2_RESETN_REGOFF)
#define HWIO_MIPI_TX_CSI2_RESETN_CSI2_RESETN_RW_FLDMASK (0x1)
#define HWIO_MIPI_TX_CSI2_RESETN_CSI2_RESETN_RW_FLDSHFT (0)
#define HWIO_MIPI_TX_CSI2_RESETN_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_CSI2_RESETN_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_INT_ST_MAIN_REGOFF 0x20
#define HWIO_MIPI_TX_INT_ST_MAIN_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_ST_MAIN_REGOFF)
#define HWIO_MIPI_TX_INT_ST_MAIN_INT_ST_VPG_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_ST_MAIN_INT_ST_VPG_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_ST_MAIN_INT_ST_IDI_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_ST_MAIN_INT_ST_IDI_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_ST_MAIN_RESERVED_2_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_ST_MAIN_RESERVED_2_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_ST_MAIN_INT_ST_PHY_FLDMASK (0x8)
#define HWIO_MIPI_TX_INT_ST_MAIN_INT_ST_PHY_FLDSHFT (3)
#define HWIO_MIPI_TX_INT_ST_MAIN_RESERVED_31_4_FLDMASK (0xfffffff0)
#define HWIO_MIPI_TX_INT_ST_MAIN_RESERVED_31_4_FLDSHFT (4)

#define HWIO_MIPI_TX_INT_ST_VPG_REGOFF 0x24
#define HWIO_MIPI_TX_INT_ST_VPG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_ST_VPG_REGOFF)
#define HWIO_MIPI_TX_INT_ST_VPG_VPG_PKT_LOST_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_ST_VPG_VPG_PKT_LOST_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_ST_VPG_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_INT_ST_VPG_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_INT_ST_IDI_REGOFF 0x28
#define HWIO_MIPI_TX_INT_ST_IDI_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_ST_IDI_REGOFF)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_ERRWC_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_ERRWC_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC0_ERRF_SEQ_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC0_ERRF_SEQ_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC1_ERRF_SEQ_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC1_ERRF_SEQ_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC2_ERRF_SEQ_FLDMASK (0x8)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC2_ERRF_SEQ_FLDSHFT (3)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC3_ERRF_SEQ_FLDMASK (0x10)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC3_ERRF_SEQ_FLDSHFT (4)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC0_ERRL_SEQ_FLDMASK (0x20)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC0_ERRL_SEQ_FLDSHFT (5)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC1_ERRL_SEQ_FLDMASK (0x40)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC1_ERRL_SEQ_FLDSHFT (6)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC2_ERRL_SEQ_FLDMASK (0x80)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC2_ERRL_SEQ_FLDSHFT (7)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC3_ERRL_SEQ_FLDMASK (0x100)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_VC3_ERRL_SEQ_FLDSHFT (8)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_FIFO_OVERFLOW_FLDMASK (0x200)
#define HWIO_MIPI_TX_INT_ST_IDI_IDI_FIFO_OVERFLOW_FLDSHFT (9)
#define HWIO_MIPI_TX_INT_ST_IDI_RESERVED_31_10_FLDMASK (0xfffffc00)
#define HWIO_MIPI_TX_INT_ST_IDI_RESERVED_31_10_FLDSHFT (10)

#define HWIO_MIPI_TX_INT_ST_PHY_REGOFF 0x30
#define HWIO_MIPI_TX_INT_ST_PHY_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_ST_PHY_REGOFF)
#define HWIO_MIPI_TX_INT_ST_PHY_TO_HS_TX_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_ST_PHY_TO_HS_TX_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_ST_PHY_ERRCONTENTIONLP0_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_ST_PHY_ERRCONTENTIONLP0_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_ST_PHY_ERRCONTENTIONLP1_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_ST_PHY_ERRCONTENTIONLP1_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_ST_PHY_RESERVED_31_3_FLDMASK (0xfffffff8)
#define HWIO_MIPI_TX_INT_ST_PHY_RESERVED_31_3_FLDSHFT (3)

#define HWIO_MIPI_TX_INT_MASK_N_VPG_REGOFF 0x40
#define HWIO_MIPI_TX_INT_MASK_N_VPG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_MASK_N_VPG_REGOFF)
#define HWIO_MIPI_TX_INT_MASK_N_VPG_MASK_VPG_PKT_LOST_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_MASK_N_VPG_MASK_VPG_PKT_LOST_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_MASK_N_VPG_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_INT_MASK_N_VPG_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_INT_FORCE_VPG_REGOFF 0x44
#define HWIO_MIPI_TX_INT_FORCE_VPG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_FORCE_VPG_REGOFF)
#define HWIO_MIPI_TX_INT_FORCE_VPG_FORCE_VPG_PKT_LOST_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_FORCE_VPG_FORCE_VPG_PKT_LOST_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_FORCE_VPG_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_INT_FORCE_VPG_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_INT_MASK_N_IDI_REGOFF 0x48
#define HWIO_MIPI_TX_INT_MASK_N_IDI_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_MASK_N_IDI_REGOFF)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_ERRWC_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_ERRWC_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC0_ERRF_SEQ_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC0_ERRF_SEQ_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC1_ERRF_SEQ_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC1_ERRF_SEQ_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC2_ERRF_SEQ_FLDMASK (0x8)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC2_ERRF_SEQ_FLDSHFT (3)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC3_ERRF_SEQ_FLDMASK (0x10)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC3_ERRF_SEQ_FLDSHFT (4)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC0_ERRL_SEQ_FLDMASK (0x20)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC0_ERRL_SEQ_FLDSHFT (5)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC1_ERRL_SEQ_FLDMASK (0x40)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC1_ERRL_SEQ_FLDSHFT (6)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC2_ERRL_SEQ_FLDMASK (0x80)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC2_ERRL_SEQ_FLDSHFT (7)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC3_ERRL_SEQ_FLDMASK (0x100)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_VC3_ERRL_SEQ_FLDSHFT (8)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_FIFO_OVERFLOW_FLDMASK (0x200)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_MASK_IDI_FIFO_OVERFLOW_FLDSHFT (9)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_RESERVED_31_10_FLDMASK (0xfffffc00)
#define HWIO_MIPI_TX_INT_MASK_N_IDI_RESERVED_31_10_FLDSHFT (10)

#define HWIO_MIPI_TX_INT_FORCE_IDI_REGOFF 0x4c
#define HWIO_MIPI_TX_INT_FORCE_IDI_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_FORCE_IDI_REGOFF)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_ERRWC_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_ERRWC_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC0_ERRF_SEQ_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC0_ERRF_SEQ_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC1_ERRF_SEQ_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC1_ERRF_SEQ_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC2_ERRF_SEQ_FLDMASK (0x8)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC2_ERRF_SEQ_FLDSHFT (3)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC3_ERRF_SEQ_FLDMASK (0x10)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC3_ERRF_SEQ_FLDSHFT (4)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC0_ERRL_SEQ_FLDMASK (0x20)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC0_ERRL_SEQ_FLDSHFT (5)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC1_ERRL_SEQ_FLDMASK (0x40)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC1_ERRL_SEQ_FLDSHFT (6)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC2_ERRL_SEQ_FLDMASK (0x80)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC2_ERRL_SEQ_FLDSHFT (7)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC3_ERRL_SEQ_FLDMASK (0x100)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_VC3_ERRL_SEQ_FLDSHFT (8)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_FIFO_OVERFLOW_FLDMASK (0x200)
#define HWIO_MIPI_TX_INT_FORCE_IDI_FORCE_IDI_FIFO_OVERFLOW_FLDSHFT (9)
#define HWIO_MIPI_TX_INT_FORCE_IDI_RESERVED_31_10_FLDMASK (0xfffffc00)
#define HWIO_MIPI_TX_INT_FORCE_IDI_RESERVED_31_10_FLDSHFT (10)

#define HWIO_MIPI_TX_INT_MASK_N_PHY_REGOFF 0x58
#define HWIO_MIPI_TX_INT_MASK_N_PHY_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_MASK_N_PHY_REGOFF)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_MASK_TO_HS_TX_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_MASK_TO_HS_TX_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_MASK_ERRCONTENTIONLP0_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_MASK_ERRCONTENTIONLP0_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_MASK_ERRCONTENTIONLP1_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_MASK_ERRCONTENTIONLP1_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_RESERVED_31_3_FLDMASK (0xfffffff8)
#define HWIO_MIPI_TX_INT_MASK_N_PHY_RESERVED_31_3_FLDSHFT (3)

#define HWIO_MIPI_TX_INT_FORCE_PHY_REGOFF 0x5c
#define HWIO_MIPI_TX_INT_FORCE_PHY_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_INT_FORCE_PHY_REGOFF)
#define HWIO_MIPI_TX_INT_FORCE_PHY_FORCE_TO_HS_TX_FLDMASK (0x1)
#define HWIO_MIPI_TX_INT_FORCE_PHY_FORCE_TO_HS_TX_FLDSHFT (0)
#define HWIO_MIPI_TX_INT_FORCE_PHY_FORCE_ERRCONTENTIONLP0_FLDMASK (0x2)
#define HWIO_MIPI_TX_INT_FORCE_PHY_FORCE_ERRCONTENTIONLP0_FLDSHFT (1)
#define HWIO_MIPI_TX_INT_FORCE_PHY_FORCE_ERRCONTENTIONLP1_FLDMASK (0x4)
#define HWIO_MIPI_TX_INT_FORCE_PHY_FORCE_ERRCONTENTIONLP1_FLDSHFT (2)
#define HWIO_MIPI_TX_INT_FORCE_PHY_RESERVED_31_3_FLDMASK (0xfffffff8)
#define HWIO_MIPI_TX_INT_FORCE_PHY_RESERVED_31_3_FLDSHFT (3)

#define HWIO_MIPI_TX_VPG_CTRL_REGOFF 0x80
#define HWIO_MIPI_TX_VPG_CTRL_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_CTRL_REGOFF)
#define HWIO_MIPI_TX_VPG_CTRL_VPG_EN_FLDMASK (0x1)
#define HWIO_MIPI_TX_VPG_CTRL_VPG_EN_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_CTRL_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_VPG_CTRL_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_VPG_STATUS_REGOFF 0x84
#define HWIO_MIPI_TX_VPG_STATUS_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_STATUS_REGOFF)
#define HWIO_MIPI_TX_VPG_STATUS_VPG_ACTIVE_FLDMASK (0x1)
#define HWIO_MIPI_TX_VPG_STATUS_VPG_ACTIVE_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_STATUS_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_VPG_STATUS_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_VPG_MODE_CFG_REGOFF 0x88
#define HWIO_MIPI_TX_VPG_MODE_CFG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_MODE_CFG_REGOFF)
#define HWIO_MIPI_TX_VPG_MODE_CFG_VPG_MODE_FLDMASK (0x1)
#define HWIO_MIPI_TX_VPG_MODE_CFG_VPG_MODE_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_MODE_CFG_RESERVED_15_1_FLDMASK (0xfffe)
#define HWIO_MIPI_TX_VPG_MODE_CFG_RESERVED_15_1_FLDSHFT (1)
#define HWIO_MIPI_TX_VPG_MODE_CFG_VPG_ORIENTATION_FLDMASK (0x10000)
#define HWIO_MIPI_TX_VPG_MODE_CFG_VPG_ORIENTATION_FLDSHFT (16)
#define HWIO_MIPI_TX_VPG_MODE_CFG_RESERVED_31_17_FLDMASK (0xfffe0000)
#define HWIO_MIPI_TX_VPG_MODE_CFG_RESERVED_31_17_FLDSHFT (17)

#define HWIO_MIPI_TX_VPG_PKT_CFG_REGOFF 0x8c
#define HWIO_MIPI_TX_VPG_PKT_CFG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_PKT_CFG_REGOFF)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_DT_FLDMASK (0x3f)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_DT_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_VC_FLDMASK (0xc0)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_VC_FLDSHFT (6)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_HSYNC_PKT_EN_FLDMASK (0x100)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_HSYNC_PKT_EN_FLDSHFT (8)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_LINE_NUM_MODE_FLDMASK (0x600)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_LINE_NUM_MODE_FLDSHFT (9)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_FRAME_NUM_MODE_FLDMASK (0x800)
#define HWIO_MIPI_TX_VPG_PKT_CFG_VPG_FRAME_NUM_MODE_FLDSHFT (11)
#define HWIO_MIPI_TX_VPG_PKT_CFG_RESERVED_31_12_FLDMASK (0xfffff000)
#define HWIO_MIPI_TX_VPG_PKT_CFG_RESERVED_31_12_FLDSHFT (12)

#define HWIO_MIPI_TX_VPG_PKT_SIZE_REGOFF 0x90
#define HWIO_MIPI_TX_VPG_PKT_SIZE_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_PKT_SIZE_REGOFF)
#define HWIO_MIPI_TX_VPG_PKT_SIZE_VPG_PKT_SIZE_FLDMASK (0x3fff)
#define HWIO_MIPI_TX_VPG_PKT_SIZE_VPG_PKT_SIZE_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_PKT_SIZE_RESERVED_31_14_FLDMASK (0xffffc000)
#define HWIO_MIPI_TX_VPG_PKT_SIZE_RESERVED_31_14_FLDSHFT (14)

#define HWIO_MIPI_TX_VPG_HSA_TIME_REGOFF 0x94
#define HWIO_MIPI_TX_VPG_HSA_TIME_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_HSA_TIME_REGOFF)
#define HWIO_MIPI_TX_VPG_HSA_TIME_VPG_HSA_TIME_FLDMASK (0xfff)
#define HWIO_MIPI_TX_VPG_HSA_TIME_VPG_HSA_TIME_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_HSA_TIME_RESERVED_31_12_FLDMASK (0xfffff000)
#define HWIO_MIPI_TX_VPG_HSA_TIME_RESERVED_31_12_FLDSHFT (12)

#define HWIO_MIPI_TX_VPG_HBP_TIME_REGOFF 0x98
#define HWIO_MIPI_TX_VPG_HBP_TIME_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_HBP_TIME_REGOFF)
#define HWIO_MIPI_TX_VPG_HBP_TIME_VPG_HBP_TIME_FLDMASK (0xfff)
#define HWIO_MIPI_TX_VPG_HBP_TIME_VPG_HBP_TIME_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_HBP_TIME_RESERVED_31_12_FLDMASK (0xfffff000)
#define HWIO_MIPI_TX_VPG_HBP_TIME_RESERVED_31_12_FLDSHFT (12)

#define HWIO_MIPI_TX_VPG_HLINE_TIME_REGOFF 0x9c
#define HWIO_MIPI_TX_VPG_HLINE_TIME_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_HLINE_TIME_REGOFF)
#define HWIO_MIPI_TX_VPG_HLINE_TIME_VPG_HLINE_TIME_FLDMASK (0x7fff)
#define HWIO_MIPI_TX_VPG_HLINE_TIME_VPG_HLINE_TIME_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_HLINE_TIME_RESERVED_31_15_FLDMASK (0xffff8000)
#define HWIO_MIPI_TX_VPG_HLINE_TIME_RESERVED_31_15_FLDSHFT (15)

#define HWIO_MIPI_TX_VPG_VSA_LINES_REGOFF 0xa0
#define HWIO_MIPI_TX_VPG_VSA_LINES_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_VSA_LINES_REGOFF)
#define HWIO_MIPI_TX_VPG_VSA_LINES_VPG_VSA_LINES_FLDMASK (0x3ff)
#define HWIO_MIPI_TX_VPG_VSA_LINES_VPG_VSA_LINES_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_VSA_LINES_RESERVED_31_10_FLDMASK (0xfffffc00)
#define HWIO_MIPI_TX_VPG_VSA_LINES_RESERVED_31_10_FLDSHFT (10)

#define HWIO_MIPI_TX_VPG_VBP_LINES_REGOFF 0xa4
#define HWIO_MIPI_TX_VPG_VBP_LINES_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_VBP_LINES_REGOFF)
#define HWIO_MIPI_TX_VPG_VBP_LINES_VPG_VBP_LINES_FLDMASK (0x3ff)
#define HWIO_MIPI_TX_VPG_VBP_LINES_VPG_VBP_LINES_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_VBP_LINES_RESERVED_31_10_FLDMASK (0xfffffc00)
#define HWIO_MIPI_TX_VPG_VBP_LINES_RESERVED_31_10_FLDSHFT (10)

#define HWIO_MIPI_TX_VPG_VFP_LINES_REGOFF 0xa8
#define HWIO_MIPI_TX_VPG_VFP_LINES_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_VFP_LINES_REGOFF)
#define HWIO_MIPI_TX_VPG_VFP_LINES_VPG_VFP_LINES_FLDMASK (0x3ff)
#define HWIO_MIPI_TX_VPG_VFP_LINES_VPG_VFP_LINES_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_VFP_LINES_RESERVED_31_10_FLDMASK (0xfffffc00)
#define HWIO_MIPI_TX_VPG_VFP_LINES_RESERVED_31_10_FLDSHFT (10)

#define HWIO_MIPI_TX_VPG_ACT_LINES_REGOFF 0xac
#define HWIO_MIPI_TX_VPG_ACT_LINES_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_ACT_LINES_REGOFF)
#define HWIO_MIPI_TX_VPG_ACT_LINES_VPG_ACT_LINES_FLDMASK (0x3fff)
#define HWIO_MIPI_TX_VPG_ACT_LINES_VPG_ACT_LINES_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_ACT_LINES_RESERVED_31_14_FLDMASK (0xffffc000)
#define HWIO_MIPI_TX_VPG_ACT_LINES_RESERVED_31_14_FLDSHFT (14)

#define HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_REGOFF 0xb0
#define HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_REGOFF)
#define HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_VPG_MAX_FRAME_NUM_FLDMASK (0xffff)
#define HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_VPG_MAX_FRAME_NUM_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_RESERVED_31_16_FLDMASK (0xffff0000)
#define HWIO_MIPI_TX_VPG_MAX_FRAME_NUM_RESERVED_31_16_FLDSHFT (16)

#define HWIO_MIPI_TX_VPG_START_LINE_NUM_REGOFF 0xb4
#define HWIO_MIPI_TX_VPG_START_LINE_NUM_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_START_LINE_NUM_REGOFF)
#define HWIO_MIPI_TX_VPG_START_LINE_NUM_VPG_START_LINE_NUM_FLDMASK (0xffff)
#define HWIO_MIPI_TX_VPG_START_LINE_NUM_VPG_START_LINE_NUM_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_START_LINE_NUM_RESERVED_31_16_FLDMASK (0xffff0000)
#define HWIO_MIPI_TX_VPG_START_LINE_NUM_RESERVED_31_16_FLDSHFT (16)

#define HWIO_MIPI_TX_VPG_STEP_LINE_NUM_REGOFF 0xb8
#define HWIO_MIPI_TX_VPG_STEP_LINE_NUM_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_VPG_STEP_LINE_NUM_REGOFF)
#define HWIO_MIPI_TX_VPG_STEP_LINE_NUM_VPG_STEP_LINE_NUM_FLDMASK (0xffff)
#define HWIO_MIPI_TX_VPG_STEP_LINE_NUM_VPG_STEP_LINE_NUM_FLDSHFT (0)
#define HWIO_MIPI_TX_VPG_STEP_LINE_NUM_RESERVED_31_16_FLDMASK (0xffff0000)
#define HWIO_MIPI_TX_VPG_STEP_LINE_NUM_RESERVED_31_16_FLDSHFT (16)

#define HWIO_MIPI_TX_PHY_RSTZ_REGOFF 0xe0
#define HWIO_MIPI_TX_PHY_RSTZ_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY_RSTZ_REGOFF)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_SHUTDOWNZ_FLDMASK (0x1)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_SHUTDOWNZ_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_RSTZ_FLDMASK (0x2)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_RSTZ_FLDSHFT (1)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_ENABLECLK_FLDMASK (0x4)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_ENABLECLK_FLDSHFT (2)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_FORCEPLL_FLDMASK (0x8)
#define HWIO_MIPI_TX_PHY_RSTZ_PHY_FORCEPLL_FLDSHFT (3)
#define HWIO_MIPI_TX_PHY_RSTZ_RESERVED_31_4_FLDMASK (0xfffffff0)
#define HWIO_MIPI_TX_PHY_RSTZ_RESERVED_31_4_FLDSHFT (4)

#define HWIO_MIPI_TX_PHY_IF_CFG_REGOFF 0xe4
#define HWIO_MIPI_TX_PHY_IF_CFG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY_IF_CFG_REGOFF)
#define HWIO_MIPI_TX_PHY_IF_CFG_LANE_EN_NUM_FLDMASK (0x7)
#define HWIO_MIPI_TX_PHY_IF_CFG_LANE_EN_NUM_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY_IF_CFG_RESERVED_7_3_FLDMASK (0xf8)
#define HWIO_MIPI_TX_PHY_IF_CFG_RESERVED_7_3_FLDSHFT (3)
#define HWIO_MIPI_TX_PHY_IF_CFG_PHY_STOP_WAIT_TIME_FLDMASK (0xff00)
#define HWIO_MIPI_TX_PHY_IF_CFG_PHY_STOP_WAIT_TIME_FLDSHFT (8)
#define HWIO_MIPI_TX_PHY_IF_CFG_RESERVED_31_16_FLDMASK (0xffff0000)
#define HWIO_MIPI_TX_PHY_IF_CFG_RESERVED_31_16_FLDSHFT (16)

#define HWIO_MIPI_TX_LPCLK_CTRL_REGOFF 0xe8
#define HWIO_MIPI_TX_LPCLK_CTRL_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_LPCLK_CTRL_REGOFF)
#define HWIO_MIPI_TX_LPCLK_CTRL_PHY_TXREQCLKHS_CON_FLDMASK (0x1)
#define HWIO_MIPI_TX_LPCLK_CTRL_PHY_TXREQCLKHS_CON_FLDSHFT (0)
#define HWIO_MIPI_TX_LPCLK_CTRL_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_LPCLK_CTRL_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_PHY_ULPS_CTRL_REGOFF 0xec
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY_ULPS_CTRL_REGOFF)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXREQULPSCLK_FLDMASK (0x1)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXREQULPSCLK_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXEXITULPSCLK_FLDMASK (0x2)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXEXITULPSCLK_FLDSHFT (1)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXREQULPSLAN_FLDMASK (0x4)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXREQULPSLAN_FLDSHFT (2)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXEXITULPSLAN_FLDMASK (0x8)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_PHY_TXEXITULPSLAN_FLDSHFT (3)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_RESERVED_31_4_FLDMASK (0xfffffff0)
#define HWIO_MIPI_TX_PHY_ULPS_CTRL_RESERVED_31_4_FLDSHFT (4)

#define HWIO_MIPI_TX_CLKMGR_CFG_REGOFF 0xf0
#define HWIO_MIPI_TX_CLKMGR_CFG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_CLKMGR_CFG_REGOFF)
#define HWIO_MIPI_TX_CLKMGR_CFG_TX_ESC_CLK_DIVISION_FLDMASK (0xff)
#define HWIO_MIPI_TX_CLKMGR_CFG_TX_ESC_CLK_DIVISION_FLDSHFT (0)
#define HWIO_MIPI_TX_CLKMGR_CFG_TO_CLK_DIVISION_FLDMASK (0xff00)
#define HWIO_MIPI_TX_CLKMGR_CFG_TO_CLK_DIVISION_FLDSHFT (8)
#define HWIO_MIPI_TX_CLKMGR_CFG_RESERVED_31_16_FLDMASK (0xffff0000)
#define HWIO_MIPI_TX_CLKMGR_CFG_RESERVED_31_16_FLDSHFT (16)

#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_REGOFF 0xf4
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY_TX_TRIGGERS_REGOFF)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_TX_TRIGGERS_FLDMASK (0x3)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_TX_TRIGGERS_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_RESERVED_6_2_FLDMASK (0x7c)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_RESERVED_6_2_FLDSHFT (2)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_TX_TRIGGERS_EN_FLDMASK (0x80)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_TX_TRIGGERS_EN_FLDSHFT (7)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_RESERVED_31_8_FLDMASK (0xffffff00)
#define HWIO_MIPI_TX_PHY_TX_TRIGGERS_RESERVED_31_8_FLDSHFT (8)

#define HWIO_MIPI_TX_PHY_CAL_REGOFF 0xf8
#define HWIO_MIPI_TX_PHY_CAL_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY_CAL_REGOFF)
#define HWIO_MIPI_TX_PHY_CAL_PHY_CAL_FLDMASK (0x1)
#define HWIO_MIPI_TX_PHY_CAL_PHY_CAL_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY_CAL_RESERVED_31_1_FLDMASK (0xfffffffe)
#define HWIO_MIPI_TX_PHY_CAL_RESERVED_31_1_FLDSHFT (1)

#define HWIO_MIPI_TX_TO_CNT_CFG_REGOFF 0xfc
#define HWIO_MIPI_TX_TO_CNT_CFG_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_TO_CNT_CFG_REGOFF)
#define HWIO_MIPI_TX_TO_CNT_CFG_HSTX_TO_CNT_FLDMASK (0xffff)
#define HWIO_MIPI_TX_TO_CNT_CFG_HSTX_TO_CNT_FLDSHFT (0)
#define HWIO_MIPI_TX_TO_CNT_CFG_RESERVED_31_16_FLDMASK (0xffff0000)
#define HWIO_MIPI_TX_TO_CNT_CFG_RESERVED_31_16_FLDSHFT (16)

#define HWIO_MIPI_TX_PHY_STATUS_REGOFF 0x110
#define HWIO_MIPI_TX_PHY_STATUS_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY_STATUS_REGOFF)
#define HWIO_MIPI_TX_PHY_STATUS_LANE_MAX_NUM_FLDMASK (0x7)
#define HWIO_MIPI_TX_PHY_STATUS_LANE_MAX_NUM_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY_STATUS_PLL_LOCK_FLDMASK (0x8)
#define HWIO_MIPI_TX_PHY_STATUS_PLL_LOCK_FLDSHFT (3)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_CLK_FLDMASK (0x10)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_CLK_FLDSHFT (4)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_CLK_FLDMASK (0x20)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_CLK_FLDSHFT (5)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L0_FLDMASK (0x40)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L0_FLDSHFT (6)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L0_FLDMASK (0x80)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L0_FLDSHFT (7)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L1_FLDMASK (0x100)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L1_FLDSHFT (8)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L1_FLDMASK (0x200)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L1_FLDSHFT (9)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L2_FLDMASK (0x400)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L2_FLDSHFT (10)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L2_FLDMASK (0x800)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L2_FLDSHFT (11)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L3_FLDMASK (0x1000)
#define HWIO_MIPI_TX_PHY_STATUS_TXSTOPSTATE_L3_FLDSHFT (12)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L3_FLDMASK (0x2000)
#define HWIO_MIPI_TX_PHY_STATUS_TXULPSACTIVENOT_L3_FLDSHFT (13)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_14_FLDMASK (0x4000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_14_FLDSHFT (14)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_15_FLDMASK (0x8000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_15_FLDSHFT (15)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_16_FLDMASK (0x10000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_16_FLDSHFT (16)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_17_FLDMASK (0x20000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_17_FLDSHFT (17)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_18_FLDMASK (0x40000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_18_FLDSHFT (18)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_19_FLDMASK (0x80000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_19_FLDSHFT (19)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_20_FLDMASK (0x100000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_20_FLDSHFT (20)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_21_FLDMASK (0x200000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_21_FLDSHFT (21)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_31_22_FLDMASK (0xffc00000)
#define HWIO_MIPI_TX_PHY_STATUS_RESERVED_31_22_FLDSHFT (22)

#define HWIO_MIPI_TX_PHY0_TST_CTRL0_REGOFF 0x114
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY0_TST_CTRL0_REGOFF)
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_PHY0_TESTCLR_FLDMASK (0x1)
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_PHY0_TESTCLR_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_PHY0_TESTCLK_FLDMASK (0x2)
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_PHY0_TESTCLK_FLDSHFT (1)
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_RESERVED_31_2_FLDMASK (0xfffffffc)
#define HWIO_MIPI_TX_PHY0_TST_CTRL0_RESERVED_31_2_FLDSHFT (2)

#define HWIO_MIPI_TX_PHY0_TST_CTRL1_REGOFF 0x118
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_ADDR(bAddr, regX) \
	(bAddr + HWIO_MIPI_TX_PHY0_TST_CTRL1_REGOFF)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_PHY0_TESTDIN_FLDMASK (0xff)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_PHY0_TESTDIN_FLDSHFT (0)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_PHY0_TESTDOUT_FLDMASK (0xff00)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_PHY0_TESTDOUT_FLDSHFT (8)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_PHY0_TESTEN_FLDMASK (0x10000)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_PHY0_TESTEN_FLDSHFT (16)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_RESERVED_31_17_FLDMASK (0xfffe0000)
#define HWIO_MIPI_TX_PHY0_TST_CTRL1_RESERVED_31_17_FLDSHFT (17)

#endif /* __MNH_HWIO_MIPI_TX_ */
