#
# Makefile for the cypress cm_cp_teset.
#

# Each configuration option enables a list of files.

#add for cm_cp test
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += cm_cp_test.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += configuration.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += parameter.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += pip.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += result.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += hw_cm_cp_test.o
obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5) += libcsv.o
#end cm_cp test


