#
# Makefile for oppo's custom devices
#

obj-$(CONFIG_OPPO) += oppo.o
obj-$(CONFIG_OPPO_COMMON_SOFT)	+= oppo_project.o
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT) += oppo_shutdown_detect.o
obj-$(CONFIG_REGULATOR_FAN49103) += fan49103.o
obj-y += spi-kernel/
obj-y += oppo_sensorhub/
obj-y += dap_swd/
