#
# Makefile for the industrial I/O sensors.
#

obj-$(CONFIG_INPUT_CWSTM32) += CwMcuSensor.o
obj-$(CONFIG_SENSORS_I2C_BUS)			+= CwMcuSensor_i2c.o
obj-$(CONFIG_SENSORS_SPI_BUS)			+= CwMcuSensor_spi.o

