obj-$(CONFIG_AIRBRUSH_SM) := airbrush.o

airbrush-y :=	\
		airbrush-sm.o \
		airbrush-sm-ctrl.o \
		airbrush-clk.o \
		airbrush-bootseq.o \
		airbrush-M0-interrupt.o \
		airbrush-spi.o \
		airbrush-pmu.o \
		airbrush-power-gating.o \
		airbrush-pmic-ctrl.o \
		airbrush-debugfs.o \
		airbrush-ddr.o \
		airbrush-ppmu.o
