obj-$(CONFIG_AIRBRUSH_SM) += airbrush.o tmu/

airbrush-y +=	\
		airbrush-sm.o \
		airbrush-sm-ctrl.o \
		airbrush-clk.o \
		airbrush-bootseq.o \
		airbrush-M0-interrupt.o \
		airbrush-spi.o \
		airbrush-pmu.o \
		airbrush-power-gating.o \
		airbrush-pmic-ctrl.o \
		airbrush-ddr.o \
		airbrush-ddr-vref.o \
		airbrush-ddr-test.o \
		airbrush-ppmu.o \
		airbrush-cooling.o \
		airbrush-thermal.o \
		airbrush-sysfs.o

airbrush-$(CONFIG_AIRBRUSH_SM_DEBUGFS) += airbrush-debugfs.o
